// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/models/components"
	"github.com/shadeform/shadeform-cli/internal/sdk/sdkinternal/utils"
)

type ClustersTypesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns a ClusterTypesResponse object
	ClusterTypesResponse *components.ClusterTypesResponse
}

func (c ClustersTypesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClustersTypesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClustersTypesResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *ClustersTypesResponse) GetClusterTypesResponse() *components.ClusterTypesResponse {
	if c == nil {
		return nil
	}
	return c.ClusterTypesResponse
}
