// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: e1be9869208a

package operations

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/models/components"
)

type ClustersDeleteRequest struct {
	// The cluster id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (c *ClustersDeleteRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

type ClustersDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (c *ClustersDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}
