// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: cf01786910e8

package operations

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/models/components"
	"github.com/shadeform/shadeform-cli/internal/sdk/sdkinternal/utils"
)

type ClustersInfoRequest struct {
	// The cluster id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (c *ClustersInfoRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

type ClustersInfoResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Return a cluster object.
	Cluster *components.Cluster
}

func (c ClustersInfoResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClustersInfoResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClustersInfoResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *ClustersInfoResponse) GetCluster() *components.Cluster {
	if c == nil {
		return nil
	}
	return c.Cluster
}
