// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/models/components"
	"github.com/shadeform/shadeform-cli/internal/sdk/sdkinternal/utils"
)

type ClustersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns a ClustersResponse object.
	ClustersResponse *components.ClustersResponse
}

func (c ClustersResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClustersResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClustersResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *ClustersResponse) GetClustersResponse() *components.ClustersResponse {
	if c == nil {
		return nil
	}
	return c.ClustersResponse
}
