// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 233300725f52

package operations

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/models/components"
	"github.com/shadeform/shadeform-cli/internal/sdk/sdkinternal/utils"
)

type ClustersCreateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns a CreateClusterResponse object
	CreateClusterResponse *components.CreateClusterResponse
}

func (c ClustersCreateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClustersCreateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClustersCreateResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *ClustersCreateResponse) GetCreateClusterResponse() *components.CreateClusterResponse {
	if c == nil {
		return nil
	}
	return c.CreateClusterResponse
}
