// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 88c5f77cb7c1

package operations

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/models/components"
	"github.com/shadeform/shadeform-cli/internal/sdk/sdkinternal/utils"
)

type InstancesInfoRequest struct {
	// The instance id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (i *InstancesInfoRequest) GetID() string {
	if i == nil {
		return ""
	}
	return i.ID
}

type InstancesInfoResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Return an instance object.
	InstanceInfoResponse *components.InstanceInfoResponse
}

func (i InstancesInfoResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InstancesInfoResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InstancesInfoResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *InstancesInfoResponse) GetInstanceInfoResponse() *components.InstanceInfoResponse {
	if i == nil {
		return nil
	}
	return i.InstanceInfoResponse
}
