// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 5d2d5636aa68

package operations

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/models/components"
)

type InstancesUpdateRequest struct {
	// The instance id
	ID   string                   `pathParam:"style=simple,explode=false,name=id"`
	Body components.UpdateRequest `request:"mediaType=application/json"`
}

func (i *InstancesUpdateRequest) GetID() string {
	if i == nil {
		return ""
	}
	return i.ID
}

func (i *InstancesUpdateRequest) GetBody() components.UpdateRequest {
	if i == nil {
		return components.UpdateRequest{}
	}
	return i.Body
}

type InstancesUpdateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (i *InstancesUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}
