// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/models/components"
	"github.com/shadeform/shadeform-cli/internal/sdk/sdkinternal/utils"
)

type InstancesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns an InstancesResponse object.
	InstancesResponse *components.InstancesResponse
}

func (i InstancesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InstancesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InstancesResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *InstancesResponse) GetInstancesResponse() *components.InstancesResponse {
	if i == nil {
		return nil
	}
	return i.InstancesResponse
}
