// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/models/components"
)

type InstancesRestartRequest struct {
	// The instance id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (i *InstancesRestartRequest) GetID() string {
	if i == nil {
		return ""
	}
	return i.ID
}

type InstancesRestartResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (i *InstancesRestartResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}
