// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 7279a469fc2c

package operations

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/models/components"
	"github.com/shadeform/shadeform-cli/internal/sdk/sdkinternal/utils"
)

type InstancesCreateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns a CreateResponse object
	CreateResponse *components.CreateResponse
}

func (i InstancesCreateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InstancesCreateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InstancesCreateResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *InstancesCreateResponse) GetCreateResponse() *components.CreateResponse {
	if i == nil {
		return nil
	}
	return i.CreateResponse
}
