// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 2941d490befa

package operations

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/models/components"
)

type InstancesDeleteRequest struct {
	// The instance id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (i *InstancesDeleteRequest) GetID() string {
	if i == nil {
		return ""
	}
	return i.ID
}

type InstancesDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (i *InstancesDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}
