// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/shadeform/shadeform-cli/internal/sdk/models/components"
	"github.com/shadeform/shadeform-cli/internal/sdk/sdkinternal/utils"
)

// Sort the order of the instance type results.
type Sort string

const (
	SortPrice Sort = "price"
)

func (e Sort) ToPointer() *Sort {
	return &e
}
func (e *Sort) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "price":
		*e = Sort(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Sort: %v", v)
	}
}

type InstancesTypesRequest struct {
	// Filter the instance type results by cloud.
	Cloud *string `queryParam:"style=form,explode=true,name=cloud"`
	// Filter the instance type results by region.
	Region *string `queryParam:"style=form,explode=true,name=region"`
	// Filter the instance type results by the number of gpus.
	NumGpus *string `queryParam:"style=form,explode=true,name=num_gpus"`
	// Filter the instance type results by gpu type.
	GpuType *string `queryParam:"style=form,explode=true,name=gpu_type"`
	// Filter the instance type results by the shade instance type.
	ShadeInstanceType *string `queryParam:"style=form,explode=true,name=shade_instance_type"`
	// Filter the instance type results by availability. Applies to individual availability entries, so an instance type whose region is available only as spot is still returned with just its spot entry; filter by `rental_type` client-side if you only want on-demand.
	Available *bool `queryParam:"style=form,explode=true,name=available"`
	// Sort the order of the instance type results.
	Sort *Sort `queryParam:"style=form,explode=true,name=sort"`
}

func (i *InstancesTypesRequest) GetCloud() *string {
	if i == nil {
		return nil
	}
	return i.Cloud
}

func (i *InstancesTypesRequest) GetRegion() *string {
	if i == nil {
		return nil
	}
	return i.Region
}

func (i *InstancesTypesRequest) GetNumGpus() *string {
	if i == nil {
		return nil
	}
	return i.NumGpus
}

func (i *InstancesTypesRequest) GetGpuType() *string {
	if i == nil {
		return nil
	}
	return i.GpuType
}

func (i *InstancesTypesRequest) GetShadeInstanceType() *string {
	if i == nil {
		return nil
	}
	return i.ShadeInstanceType
}

func (i *InstancesTypesRequest) GetAvailable() *bool {
	if i == nil {
		return nil
	}
	return i.Available
}

func (i *InstancesTypesRequest) GetSort() *Sort {
	if i == nil {
		return nil
	}
	return i.Sort
}

type InstancesTypesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns an InstanceTypesResponse object
	InstanceTypesResponse *components.InstanceTypesResponse
}

func (i InstancesTypesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InstancesTypesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InstancesTypesResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *InstancesTypesResponse) GetInstanceTypesResponse() *components.InstanceTypesResponse {
	if i == nil {
		return nil
	}
	return i.InstanceTypesResponse
}
