// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c04027568b4c

package operations

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/models/components"
	"github.com/shadeform/shadeform-cli/internal/sdk/sdkinternal/utils"
)

type SSHKeysInfoRequest struct {
	// The ssh key id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (s *SSHKeysInfoRequest) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

type SSHKeysInfoResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Return an SshKey object.
	SSHKey *components.SSHKey
}

func (s SSHKeysInfoResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSHKeysInfoResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SSHKeysInfoResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *SSHKeysInfoResponse) GetSSHKey() *components.SSHKey {
	if s == nil {
		return nil
	}
	return s.SSHKey
}
