// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/models/components"
	"github.com/shadeform/shadeform-cli/internal/sdk/sdkinternal/utils"
)

type SSHKeysResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns an SSHKeysResponse object
	SSHKeysResponse *components.SSHKeysResponse
}

func (s SSHKeysResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSHKeysResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SSHKeysResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *SSHKeysResponse) GetSSHKeysResponse() *components.SSHKeysResponse {
	if s == nil {
		return nil
	}
	return s.SSHKeysResponse
}
