// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/models/components"
	"github.com/shadeform/shadeform-cli/internal/sdk/sdkinternal/utils"
)

type SSHKeysAddResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns a AddSshKeyResponse object
	AddSSHKeyResponse *components.AddSSHKeyResponse
}

func (s SSHKeysAddResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSHKeysAddResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SSHKeysAddResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *SSHKeysAddResponse) GetAddSSHKeyResponse() *components.AddSSHKeyResponse {
	if s == nil {
		return nil
	}
	return s.AddSSHKeyResponse
}
