// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 99331a4ef591

package operations

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/models/components"
)

type SSHKeysSetDefaultRequest struct {
	// The ssh key id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (s *SSHKeysSetDefaultRequest) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

type SSHKeysSetDefaultResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (s *SSHKeysSetDefaultResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}
