// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/models/components"
)

type SSHKeysDeleteRequest struct {
	// The ssh key id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (s *SSHKeysDeleteRequest) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

type SSHKeysDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (s *SSHKeysDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}
