// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/models/components"
)

type TemplatesUpdateRequest struct {
	// The template ID
	TemplateID string                         `pathParam:"style=simple,explode=false,name=template_id"`
	Body       components.TemplateSaveRequest `request:"mediaType=application/json"`
}

func (t *TemplatesUpdateRequest) GetTemplateID() string {
	if t == nil {
		return ""
	}
	return t.TemplateID
}

func (t *TemplatesUpdateRequest) GetBody() components.TemplateSaveRequest {
	if t == nil {
		return components.TemplateSaveRequest{}
	}
	return t.Body
}

type TemplatesUpdateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (t *TemplatesUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if t == nil {
		return components.HTTPMetadata{}
	}
	return t.HTTPMeta
}
