// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 9c4b8af710fc

package operations

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/models/components"
)

type TemplatesDeleteRequest struct {
	// The template ID
	TemplateID string `pathParam:"style=simple,explode=false,name=template_id"`
}

func (t *TemplatesDeleteRequest) GetTemplateID() string {
	if t == nil {
		return ""
	}
	return t.TemplateID
}

type TemplatesDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (t *TemplatesDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if t == nil {
		return components.HTTPMetadata{}
	}
	return t.HTTPMeta
}
