// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/models/components"
	"github.com/shadeform/shadeform-cli/internal/sdk/sdkinternal/utils"
)

type TemplatesInfoRequest struct {
	// The template ID
	TemplateID string `pathParam:"style=simple,explode=false,name=template_id"`
}

func (t *TemplatesInfoRequest) GetTemplateID() string {
	if t == nil {
		return ""
	}
	return t.TemplateID
}

type TemplatesInfoResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns template information
	Template *components.Template
}

func (t TemplatesInfoResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TemplatesInfoResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TemplatesInfoResponse) GetHTTPMeta() components.HTTPMetadata {
	if t == nil {
		return components.HTTPMetadata{}
	}
	return t.HTTPMeta
}

func (t *TemplatesInfoResponse) GetTemplate() *components.Template {
	if t == nil {
		return nil
	}
	return t.Template
}
