// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/models/components"
	"github.com/shadeform/shadeform-cli/internal/sdk/sdkinternal/utils"
)

type TemplatesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns a list of templates
	TemplatesResponse *components.TemplatesResponse
}

func (t TemplatesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TemplatesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TemplatesResponse) GetHTTPMeta() components.HTTPMetadata {
	if t == nil {
		return components.HTTPMetadata{}
	}
	return t.HTTPMeta
}

func (t *TemplatesResponse) GetTemplatesResponse() *components.TemplatesResponse {
	if t == nil {
		return nil
	}
	return t.TemplatesResponse
}
