// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/models/components"
	"github.com/shadeform/shadeform-cli/internal/sdk/sdkinternal/utils"
)

type TemplatesFeaturedResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns a list of featured templates
	TemplatesResponse *components.TemplatesResponse
}

func (t TemplatesFeaturedResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TemplatesFeaturedResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TemplatesFeaturedResponse) GetHTTPMeta() components.HTTPMetadata {
	if t == nil {
		return components.HTTPMetadata{}
	}
	return t.HTTPMeta
}

func (t *TemplatesFeaturedResponse) GetTemplatesResponse() *components.TemplatesResponse {
	if t == nil {
		return nil
	}
	return t.TemplatesResponse
}
