// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: cabf44f800c3

package operations

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/models/components"
	"github.com/shadeform/shadeform-cli/internal/sdk/sdkinternal/utils"
)

type TemplatesSaveResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns a TemplateCreateResponse object
	TemplateCreateResponse *components.TemplateCreateResponse
}

func (t TemplatesSaveResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TemplatesSaveResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TemplatesSaveResponse) GetHTTPMeta() components.HTTPMetadata {
	if t == nil {
		return components.HTTPMetadata{}
	}
	return t.HTTPMeta
}

func (t *TemplatesSaveResponse) GetTemplateCreateResponse() *components.TemplateCreateResponse {
	if t == nil {
		return nil
	}
	return t.TemplateCreateResponse
}
