// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/models/components"
	"github.com/shadeform/shadeform-cli/internal/sdk/sdkinternal/utils"
)

type VolumesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns an VolumesResponse object
	VolumesResponse *components.VolumesResponse
}

func (v VolumesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VolumesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VolumesResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *VolumesResponse) GetVolumesResponse() *components.VolumesResponse {
	if v == nil {
		return nil
	}
	return v.VolumesResponse
}
