// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/models/components"
	"github.com/shadeform/shadeform-cli/internal/sdk/sdkinternal/utils"
)

type VolumesInfoRequest struct {
	// The volume id.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (v *VolumesInfoRequest) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

type VolumesInfoResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Return a volume object.
	Volume *components.Volume
}

func (v VolumesInfoResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VolumesInfoResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VolumesInfoResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *VolumesInfoResponse) GetVolume() *components.Volume {
	if v == nil {
		return nil
	}
	return v.Volume
}
