// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/models/components"
)

type VolumesDeleteRequest struct {
	// The volume id.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (v *VolumesDeleteRequest) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

type VolumesDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (v *VolumesDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}
