// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/models/components"
	"github.com/shadeform/shadeform-cli/internal/sdk/sdkinternal/utils"
)

type VolumesTypesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns an VolumesTypesResponse object.
	VolumesTypesResponse *components.VolumesTypesResponse
}

func (v VolumesTypesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VolumesTypesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VolumesTypesResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *VolumesTypesResponse) GetVolumesTypesResponse() *components.VolumesTypesResponse {
	if v == nil {
		return nil
	}
	return v.VolumesTypesResponse
}
