// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/models/components"
	"github.com/shadeform/shadeform-cli/internal/sdk/sdkinternal/utils"
)

type VolumesCreateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Returns a CreateVolumeResponse object
	CreateVolumeResponse *components.CreateVolumeResponse
}

func (v VolumesCreateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VolumesCreateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VolumesCreateResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *VolumesCreateResponse) GetCreateVolumeResponse() *components.CreateVolumeResponse {
	if v == nil {
		return nil
	}
	return v.CreateVolumeResponse
}
