// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ee877f569b53

package volumes

import (
	"github.com/shadeform/shadeform-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitVolumesRoot(parent *cobra.Command) error {
	var VolumesCmd = &cobra.Command{
		Use:         "volumes",
		Short:       "Create, inspect and delete persistent storage volumes",
		Long:        "Create, inspect and delete persistent storage volumes.",
		Args:        cobra.NoArgs,
		Annotations: map[string]string{"speakeasy_cli_group": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initListCmd(VolumesCmd); err != nil {
		return err
	}

	if err := initCreateCmd(VolumesCmd); err != nil {
		return err
	}

	if err := initDeleteCmd(VolumesCmd); err != nil {
		return err
	}

	if err := initGetCmd(VolumesCmd); err != nil {
		return err
	}

	if err := initListTypesCmd(VolumesCmd); err != nil {
		return err
	}

	parent.AddCommand(VolumesCmd)
	return nil
}
