// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdk

// Generated from OpenAPI doc version 1.0.0 and generator version 2.943.0

import (
	"context"
	"fmt"
	"github.com/shadeform/shadeform-cli/internal/sdk/models/components"
	"github.com/shadeform/shadeform-cli/internal/sdk/retry"
	"github.com/shadeform/shadeform-cli/internal/sdk/sdkinternal/config"
	"github.com/shadeform/shadeform-cli/internal/sdk/sdkinternal/hooks"
	"github.com/shadeform/shadeform-cli/internal/sdk/sdkinternal/utils"
	"net/http"
	"time"
)

// ServerList contains the list of servers available to the SDK
var ServerList = []string{
	// Shadeform Production
	"https://api.shadeform.ai/v1",
}

// HTTPClient provides an interface for supplying the SDK with a custom HTTP client
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// String provides a helper function to return a pointer to a string
func String(s string) *string { return &s }

// Bool provides a helper function to return a pointer to a bool
func Bool(b bool) *bool { return &b }

// Int provides a helper function to return a pointer to an int
func Int(i int) *int { return &i }

// Int64 provides a helper function to return a pointer to an int64
func Int64(i int64) *int64 { return &i }

// Float32 provides a helper function to return a pointer to a float32
func Float32(f float32) *float32 { return &f }

// Float64 provides a helper function to return a pointer to a float64
func Float64(f float64) *float64 { return &f }

// Pointer provides a helper function to return a pointer to a type
func Pointer[T any](v T) *T { return &v }

// Shadeform API: Shadeform is a single API and platform for deploying and managing cloud GPUs.
type Shadeform struct {
	SDKVersion string
	// Create, inspect, update, restart and delete GPU instances.
	Instances *Instances
	// Create, inspect and delete multi-node GPU clusters.
	Clusters *Clusters
	// Manage SSH keys used to access instances.
	SSHKeys *SSHKeys
	// Create, inspect and delete persistent storage volumes.
	Volumes *Volumes
	// Save and reuse launch configurations as templates.
	Templates *Templates

	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

type SDKOption func(*Shadeform)

// WithServerURL allows providing an alternative server URL
func WithServerURL(serverURL string) SDKOption {
	return func(sdk *Shadeform) {
		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithTemplatedServerURL allows the overriding of the default server URL with a templated URL populated with the provided parameters
func WithTemplatedServerURL(serverURL string, params map[string]string) SDKOption {
	return func(sdk *Shadeform) {
		if params != nil {
			serverURL = utils.ReplaceParameters(serverURL, params)
		}

		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithServerIndex allows the overriding of the default server by index
func WithServerIndex(serverIndex int) SDKOption {
	return func(sdk *Shadeform) {
		if serverIndex < 0 || serverIndex >= len(ServerList) {
			panic(fmt.Errorf("server index %d out of range", serverIndex))
		}

		sdk.sdkConfiguration.ServerIndex = serverIndex
	}
}

// WithClient allows the overriding of the default HTTP client used by the SDK
func WithClient(client HTTPClient) SDKOption {
	return func(sdk *Shadeform) {
		sdk.sdkConfiguration.Client = client
	}
}

// WithSecurity configures the SDK to use the provided security details
func WithSecurity(security components.Security) SDKOption {
	return func(sdk *Shadeform) {
		sdk.sdkConfiguration.Security = utils.AsSecuritySource(security)
	}
}

// WithSecuritySource configures the SDK to invoke the Security Source function on each method call to determine authentication
func WithSecuritySource(security func(context.Context) (components.Security, error)) SDKOption {
	return func(sdk *Shadeform) {
		sdk.sdkConfiguration.Security = func(ctx context.Context) (interface{}, error) {
			return security(ctx)
		}
	}
}

func WithRetryConfig(retryConfig retry.Config) SDKOption {
	return func(sdk *Shadeform) {
		sdk.sdkConfiguration.RetryConfig = &retryConfig
	}
}

// WithTimeout Optional request timeout applied to each operation
func WithTimeout(timeout time.Duration) SDKOption {
	return func(sdk *Shadeform) {
		sdk.sdkConfiguration.Timeout = &timeout
	}
}

// New creates a new instance of the SDK with the provided options
func New(opts ...SDKOption) *Shadeform {
	sdk := &Shadeform{
		SDKVersion: "0.1.2",
		sdkConfiguration: config.SDKConfiguration{
			UserAgent:         "speakeasy-sdk/go 0.1.2 2.943.0 1.0.0 github.com/shadeform/shadeform-cli/internal/sdk",
			SDKVersion:        "0.1.2",
			GenVersion:        "2.943.0",
			OpenAPIDocVersion: "1.0.0",
			ServerList:        ServerList,
		},
		hooks: hooks.New(),
	}
	for _, opt := range opts {
		opt(sdk)
	}

	// Use WithClient to override the default client if you would like to customize the timeout
	if sdk.sdkConfiguration.Client == nil {
		sdk.sdkConfiguration.Client = &http.Client{Timeout: 60 * time.Second}
	}

	sdk.sdkConfiguration = sdk.hooks.SDKInit(sdk.sdkConfiguration)

	sdk.Instances = newInstances(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Clusters = newClusters(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.SSHKeys = newSSHKeys(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Volumes = newVolumes(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Templates = newTemplates(sdk, sdk.sdkConfiguration, sdk.hooks)

	return sdk
}
