// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sshkeys

import (
	"fmt"
	"github.com/shadeform/shadeform-cli/internal/client"
	"github.com/shadeform/shadeform-cli/internal/flagutil"
	"github.com/shadeform/shadeform-cli/internal/output"
	"github.com/shadeform/shadeform-cli/internal/sdk"
	"github.com/shadeform/shadeform-cli/internal/sdk/models/components"
	"github.com/shadeform/shadeform-cli/internal/sdk/models/operations"
	"github.com/shadeform/shadeform-cli/internal/usage"
	"github.com/spf13/cobra"
)

var addCmdMeta = []flagutil.FlagMeta{
	{FlagName: "name", Shorthand: "n", FieldPath: "Name", Kind: flagutil.FlagKindString, Required: true, Description: "The name of the SSH Key. [required]"},
	{FlagName: "public-key", Shorthand: "p", FieldPath: "PublicKey", Kind: flagutil.FlagKindString, Required: true, Description: "The public key. [required]"},
}

// initAddCmd initializes the add command.
func initAddCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "add",
		Short:   "Add an SSH key",
		Long:    "Add a new SSH Key",
		Example: "  shade ssh-keys add --name 'My ssh key' --public-key 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAklOUpkDHrfHY17SbrmTIpNLTGK9Tjom/BWDSU GPl+nafzlHDTYW7hdI4yZ5ew18JH4JW9jbhUFrviQzM7xlELEVf4h9lFX5QVkbPppSwg0cda3 Pbv7kOdJ/MTyBlWXFCR+HAo3FXRitBqxiX1nKhXpHAZsMciLq8V6RjsNAQwdsdMFvSlVK/7XA t3FaoJoAsncM1Q9x5+3V0Ww68/eIFmb1zuUFljQJKprrX88XypNDvjYNby6vw/Pb0rwert/En mZ+AW4OZPnTPI89ZPmVMLuayrD2cE86Z/il8b+gw3r3+1nKatmIkjn2so1d01QraTlMqVSsbx NrRFi9wrf+M7Q== schacon@mylaptop.local'",
		Args:    cobra.NoArgs,
		RunE:    runAddCmd,
		Annotations: map[string]string{
			"speakeasy_operation": "SshKeysAdd",
		},
	}
	flagutil.RegisterFlags(cmd, addCmdMeta)
	if err := flagutil.ValidateMeta[components.AddSSHKeyRequest](addCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for add: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin; @path reads a file, @- reads stdin to EOF. Use --schema to print the exact JSON Schema.")
	_ = flagutil.AnnotatePromptFlag(cmd, "body", flagutil.PromptFlagSpec{Kind: "json", BodyFlag: true})
	cmd.Annotations[flagutil.AnnotationWholeBodyFlag] = "body"
	if err := flagutil.AnnotateBodyFields(cmd, addCmdMeta, "", "body"); err != nil {
		return fmt.Errorf("annotate body fields for add: %w", err)
	}
	cmd.Flags().Bool("schema", false, "Print the exact JSON Schema of the request body and exit")
	_ = flagutil.AnnotatePromptFlag(cmd, "schema", flagutil.PromptFlagSpec{Kind: "bool", DocSurface: true})
	parent.AddCommand(cmd)
	return nil
}

// runAddCmd executes the add command.
func runAddCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if requested, _ := cmd.Flags().GetBool("schema"); requested {
		return usage.EmitBodySchema(cmd.OutOrStdout(), "SshKeysAdd")
	}
	request, err := flagutil.BuildRequest[components.AddSSHKeyRequest](cmd, addCmdMeta, "", "body")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.SSHKeys.Add(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
