package sshkeys

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/shadeform/shadeform-cli/internal/client"
	"github.com/shadeform/shadeform-cli/internal/flagutil"
	"github.com/shadeform/shadeform-cli/internal/interactive"
	"github.com/shadeform/shadeform-cli/internal/output"
	"github.com/shadeform/shadeform-cli/internal/reveal"
	"github.com/shadeform/shadeform-cli/internal/sdk"
	"github.com/shadeform/shadeform-cli/internal/sdk/models/operations"
	"github.com/shadeform/shadeform-cli/internal/usage"
	"github.com/spf13/cobra"
)

// This command is hand-written (not generated by Speakeasy). It is the only
// place the CLI asks the API for an SSH private key; every other SSH key
// command has the field stripped by the RedactPrivateKeyHook.

var downloadCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "The ssh key id [required]"},
}

const (
	downloadOutFlag    = "out"
	downloadForceFlag  = "force"
	downloadStdoutFlag = "stdout"
	defaultSSHUser     = "shadeform"
)

func initDownloadCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:   "download [id]",
		Short: "Download the private key of a Shadeform-managed SSH key",
		Long: `Download the private key of a Shadeform-managed SSH key to a file.

Keys generated by Shadeform have their private half stored by the platform so
you can retrieve it later. Keys you uploaded yourself have no stored private
key, and this command reports that instead.

By default the key is written to ~/.ssh/shadeform-<name>.pem with mode 0600 and
only the path is printed. Pass --stdout to print the key itself, for example to
pipe it somewhere; nothing else in the CLI ever prints private key material.`,
		Example: `  shade ssh-keys download d290f1ee-6c54-4b01-90e6-d701748f0851
  shade ssh-keys download d290f1ee-6c54-4b01-90e6-d701748f0851 --out ./my-key.pem
  shade ssh-keys download d290f1ee-6c54-4b01-90e6-d701748f0851 --stdout > key.pem`,
		Args: flagutil.PositionalFlagArgs,
		RunE: runDownloadCmd,
		Annotations: map[string]string{
			"speakeasy_operation": "SshKeysInfo",
		},
	}
	flagutil.RegisterFlags(cmd, downloadCmdMeta)
	if err := flagutil.ValidateMeta[operations.SSHKeysInfoRequest](downloadCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for download: %w", err)
	}
	if err := flagutil.DeclarePositionalFlag(cmd, "id", "The ssh key id (or pass it as the [id] argument)", true); err != nil {
		return err
	}
	if err := interactive.Declare(cmd, interactive.CommandSpec{Args: []interactive.ArgSpec{
		{Name: "id", Summary: "The ssh key id", Required: true, SatisfiedBy: []string{"id"}},
	}}); err != nil {
		return fmt.Errorf("declare interactive arguments for download: %w", err)
	}
	cmd.Flags().String(downloadOutFlag, "", "File to write the private key to (default ~/.ssh/shadeform-<name>.pem)")
	cmd.Flags().Bool(downloadForceFlag, false, "Overwrite the output file if it already exists")
	cmd.Flags().Bool(downloadStdoutFlag, false, "Print the private key to stdout instead of writing a file")
	cmd.MarkFlagsMutuallyExclusive(downloadOutFlag, downloadStdoutFlag)
	usage.MarkDynamic(cmd)
	parent.AddCommand(cmd)
	return nil
}

// sshKeyWithSecret is the shape the info endpoint actually returns; the
// generated components.SSHKey omits private_key because the public OpenAPI
// document does not declare it.
type sshKeyWithSecret struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	PublicKey  string `json:"public_key"`
	PrivateKey string `json:"private_key"`
	IsDefault  bool   `json:"is_default"`
}

func runDownloadCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if err := flagutil.ResolvePositionalFlag(cmd, args); err != nil {
		return err
	}
	req, err := flagutil.BuildRequest[operations.SSHKeysInfoRequest](cmd, downloadCmdMeta, "", "")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}

	outPath, _ := flagutil.GetStringFlag(cmd, downloadOutFlag)
	force, _ := flagutil.GetBoolFlag(cmd, downloadForceFlag)
	toStdout, _ := flagutil.GetBoolFlag(cmd, downloadStdoutFlag)

	// Resolve and validate the destination before spending a request on it.
	if !toStdout && !client.IsDryRun(cmd) && outPath != "" {
		if err := checkWritable(outPath, force); err != nil {
			return err
		}
	}

	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	// The typed response drops private_key, so always read the raw body.
	sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())

	ctx := reveal.WithPrivateKey(cmd.Context())
	res, err := s.SSHKeys.Get(ctx, *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}
	if flagutil.DidDryRunRequest(cmd) {
		return nil
	}

	key, err := decodeSSHKey(res)
	if err != nil {
		return err
	}
	if strings.TrimSpace(key.PrivateKey) == "" {
		return noPrivateKeyError{id: key.ID, name: key.Name}
	}
	material := key.PrivateKey
	if !strings.HasSuffix(material, "\n") {
		material += "\n"
	}

	if toStdout {
		_, err := io.WriteString(cmd.OutOrStdout(), material)
		return err
	}

	if outPath == "" {
		outPath, err = defaultKeyPath(key)
		if err != nil {
			return err
		}
		if err := checkWritable(outPath, force); err != nil {
			return err
		}
	}
	absPath, err := writePrivateKey(outPath, material, force)
	if err != nil {
		return err
	}

	if output.IsMachineMode(cmd) {
		return output.LocalResult(cmd, map[string]any{
			"id":   key.ID,
			"name": key.Name,
			"path": absPath,
			"mode": "0600",
		})
	}
	out := cmd.OutOrStdout()
	fmt.Fprintf(out, "Saved private key for %q to %s (mode 0600)\n", key.Name, absPath)
	fmt.Fprintf(out, "Connect with: ssh -i %s %s@<instance-ip>\n", absPath, defaultSSHUser)
	return nil
}

func decodeSSHKey(res *operations.SSHKeysInfoResponse) (*sshKeyWithSecret, error) {
	if res == nil || res.HTTPMeta.Response == nil || res.HTTPMeta.Response.Body == nil {
		return nil, output.WithCLIReason(errors.New("empty response from the SSH key endpoint"), output.ReasonCLIProtocol)
	}
	body, err := io.ReadAll(res.HTTPMeta.Response.Body)
	_ = res.HTTPMeta.Response.Body.Close()
	if err != nil {
		return nil, output.WithCLIReason(fmt.Errorf("reading SSH key response: %w", err), output.ReasonCLIProtocol)
	}
	var key sshKeyWithSecret
	if err := json.Unmarshal(body, &key); err != nil {
		return nil, output.WithCLIReason(fmt.Errorf("decoding SSH key response: %w", err), output.ReasonCLIProtocol)
	}
	return &key, nil
}

func defaultKeyPath(key *sshKeyWithSecret) (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", output.WithCLIReason(fmt.Errorf("resolving home directory: %w", err), output.ReasonCLIRuntime)
	}
	name := slugify(key.Name)
	if name == "" {
		name = key.ID
	}
	return filepath.Join(home, ".ssh", "shadeform-"+name+".pem"), nil
}

// slugify keeps the key name recognisable in a filename without letting it
// carry path separators or shell-hostile characters.
func slugify(name string) string {
	var b strings.Builder
	lastDash := true
	for _, r := range strings.ToLower(strings.TrimSpace(name)) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '.':
			b.WriteRune(r)
			lastDash = false
		default:
			if !lastDash {
				b.WriteByte('-')
				lastDash = true
			}
		}
	}
	return strings.Trim(b.String(), "-.")
}

func expandPath(p string) (string, error) {
	if p == "~" || strings.HasPrefix(p, "~/") {
		home, err := os.UserHomeDir()
		if err != nil {
			return "", err
		}
		p = filepath.Join(home, strings.TrimPrefix(p, "~"))
	}
	return filepath.Abs(p)
}

func checkWritable(path string, force bool) error {
	abs, err := expandPath(path)
	if err != nil {
		return flagutil.WithCLIValidation(fmt.Errorf("invalid --%s %q: %w", downloadOutFlag, path, err))
	}
	info, err := os.Stat(abs)
	switch {
	case err == nil && info.IsDir():
		return flagutil.WithCLIValidation(fmt.Errorf("%s is a directory; pass a file path with --%s", abs, downloadOutFlag))
	case err == nil && !force:
		return existsError{path: abs}
	case err != nil && !errors.Is(err, os.ErrNotExist):
		return output.WithCLIReason(fmt.Errorf("checking %s: %w", abs, err), output.ReasonCLIRuntime)
	}
	return nil
}

func writePrivateKey(path, material string, force bool) (string, error) {
	abs, err := expandPath(path)
	if err != nil {
		return "", flagutil.WithCLIValidation(fmt.Errorf("invalid --%s %q: %w", downloadOutFlag, path, err))
	}
	if err := os.MkdirAll(filepath.Dir(abs), 0o700); err != nil {
		return "", output.WithCLIReason(fmt.Errorf("creating %s: %w", filepath.Dir(abs), err), output.ReasonCLIRuntime)
	}
	flags := os.O_WRONLY | os.O_CREATE | os.O_EXCL
	if force {
		flags = os.O_WRONLY | os.O_CREATE | os.O_TRUNC
	}
	f, err := os.OpenFile(abs, flags, 0o600)
	if err != nil {
		if errors.Is(err, os.ErrExist) {
			return "", existsError{path: abs}
		}
		return "", output.WithCLIReason(fmt.Errorf("writing %s: %w", abs, err), output.ReasonCLIRuntime)
	}
	if _, err := io.WriteString(f, material); err != nil {
		_ = f.Close()
		return "", output.WithCLIReason(fmt.Errorf("writing %s: %w", abs, err), output.ReasonCLIRuntime)
	}
	if err := f.Close(); err != nil {
		return "", output.WithCLIReason(fmt.Errorf("writing %s: %w", abs, err), output.ReasonCLIRuntime)
	}
	// An existing file keeps its old mode under --force; make the result 0600 regardless.
	if err := os.Chmod(abs, 0o600); err != nil {
		return "", output.WithCLIReason(fmt.Errorf("setting permissions on %s: %w", abs, err), output.ReasonCLIRuntime)
	}
	return abs, nil
}

type existsError struct{ path string }

func (e existsError) Error() string {
	return fmt.Sprintf("%s already exists", e.path)
}
func (existsError) CLIReason() string { return output.ReasonCLIValidation }
func (existsError) CLIHints() []string {
	return []string{
		"Pass --force to overwrite it, or choose another location with --out",
	}
}

type noPrivateKeyError struct{ id, name string }

func (e noPrivateKeyError) Error() string {
	return fmt.Sprintf("SSH key %q (%s) has no private key stored with Shadeform", e.name, e.id)
}
func (noPrivateKeyError) CLIReason() string { return output.ReasonCLIUnavailable }
func (noPrivateKeyError) CLIHints() []string {
	return []string{
		"This key was uploaded by you, so only you hold its private half; use the key file you already have",
		"Shadeform only stores private keys for keys it generated for you",
	}
}
