// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 2d46af5f001a

package sshkeys

import (
	"github.com/shadeform/shadeform-cli/internal/client"
	"github.com/shadeform/shadeform-cli/internal/output"
	"github.com/shadeform/shadeform-cli/internal/sdk"
	"github.com/shadeform/shadeform-cli/internal/sdk/models/operations"
	"github.com/shadeform/shadeform-cli/internal/usage"
	"github.com/spf13/cobra"
)

// initListCmd initializes the list command.
func initListCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list",
		Short:   "List SSH keys",
		Long:    "Get all SSH Keys for the account.",
		Example: "  shade ssh-keys list",
		Args:    cobra.NoArgs,
		RunE:    runListCmd,
		Annotations: map[string]string{
			"speakeasy_operation": "SshKeys",
		},
	}
	parent.AddCommand(cmd)
	return nil
}

// runListCmd executes the list command.
func runListCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.SSHKeys.List(cmd.Context(), sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
