// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a683cf4a8c88

package sshkeys

import (
	"github.com/shadeform/shadeform-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitSshKeysRoot(parent *cobra.Command) error {
	var SshKeysCmd = &cobra.Command{
		Use:         "ssh-keys",
		Short:       "Manage SSH keys used to access instances",
		Long:        "Manage SSH keys used to access instances.",
		Args:        cobra.NoArgs,
		Annotations: map[string]string{"speakeasy_cli_group": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
		Aliases: []string{"sk"},
	}

	if err := initListCmd(SshKeysCmd); err != nil {
		return err
	}

	if err := initAddCmd(SshKeysCmd); err != nil {
		return err
	}

	if err := initDeleteCmd(SshKeysCmd); err != nil {
		return err
	}

	if err := initGetCmd(SshKeysCmd); err != nil {
		return err
	}

	if err := initSetDefaultCmd(SshKeysCmd); err != nil {
		return err
	}

	parent.AddCommand(SshKeysCmd)
	return nil
}
