// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sshkeys

import (
	"fmt"
	"github.com/shadeform/shadeform-cli/internal/client"
	"github.com/shadeform/shadeform-cli/internal/flagutil"
	"github.com/shadeform/shadeform-cli/internal/interactive"
	"github.com/shadeform/shadeform-cli/internal/output"
	"github.com/shadeform/shadeform-cli/internal/sdk"
	"github.com/shadeform/shadeform-cli/internal/sdk/models/operations"
	"github.com/shadeform/shadeform-cli/internal/usage"
	"github.com/spf13/cobra"
)

var setDefaultCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "The ssh key id [required]"},
}

// initSetDefaultCmd initializes the set-default command.
func initSetDefaultCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "set-default [id]",
		Short:   "Set the default SSH key",
		Long:    "Set the specified SSH Key as the default SSH Key used by Shadeform.",
		Example: "  shade ssh-keys set-default --id d290f1ee-6c54-4b01-90e6-d701748f0851",
		Args:    flagutil.PositionalFlagArgs,
		RunE:    runSetDefaultCmd,
		Aliases: []string{"sd"},
		Annotations: map[string]string{
			"speakeasy_operation": "SshKeysSetDefault",
		},
	}
	flagutil.RegisterFlags(cmd, setDefaultCmdMeta)
	if err := flagutil.ValidateMeta[operations.SSHKeysSetDefaultRequest](setDefaultCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for set-default: %w", err)
	}
	if err := flagutil.DeclarePositionalFlag(cmd, "id", "The ssh key id (or pass it as the [id] argument)", true); err != nil {
		return err
	}
	if err := interactive.Declare(cmd, interactive.CommandSpec{Args: []interactive.ArgSpec{
		{Name: "id", Summary: "The ssh key id", Required: true, SatisfiedBy: []string{"id"}},
	}}); err != nil {
		return fmt.Errorf("declare interactive arguments for set-default: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runSetDefaultCmd executes the set-default command.
func runSetDefaultCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if err := flagutil.ResolvePositionalFlag(cmd, args); err != nil {
		return err
	}
	req, err := flagutil.BuildRequest[operations.SSHKeysSetDefaultRequest](cmd, setDefaultCmdMeta, "", "")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.SSHKeys.SetDefault(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
