// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 1ad8d3f12c48

package instances

import (
	"fmt"
	"github.com/shadeform/shadeform-cli/internal/client"
	"github.com/shadeform/shadeform-cli/internal/flagutil"
	"github.com/shadeform/shadeform-cli/internal/output"
	"github.com/shadeform/shadeform-cli/internal/sdk"
	"github.com/shadeform/shadeform-cli/internal/sdk/models/operations"
	"github.com/shadeform/shadeform-cli/internal/usage"
	"github.com/spf13/cobra"
)

var listTypesCmdMeta = []flagutil.FlagMeta{
	{FlagName: "cloud", Shorthand: "c", FieldPath: "Cloud", Kind: flagutil.FlagKindString, Optional: true, Description: "Filter the instance type results by cloud."},
	{FlagName: "region", Shorthand: "r", FieldPath: "Region", Kind: flagutil.FlagKindString, Optional: true, Description: "Filter the instance type results by region."},
	{FlagName: "num-gpus", Shorthand: "n", FieldPath: "NumGpus", Kind: flagutil.FlagKindString, Optional: true, Description: "Filter the instance type results by the number of gpus."},
	{FlagName: "gpu-type", Shorthand: "g", FieldPath: "GpuType", Kind: flagutil.FlagKindString, Optional: true, Description: "Filter the instance type results by gpu type."},
	{FlagName: "shade-instance-type", FieldPath: "ShadeInstanceType", Kind: flagutil.FlagKindString, Optional: true, Description: "Filter the instance type results by the shade instance type."},
	{FlagName: "available", Shorthand: "a", FieldPath: "Available", Kind: flagutil.FlagKindBool, Optional: true, Description: "Filter the instance type results by availability. Applies to individual availability entries, so an instance type whose region is available only as spot is still returned with just its spot entry; filter by 'rental_type' client-side if you only want on-demand."},
	{FlagName: "sort", FieldPath: "Sort", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"price"}, Description: "Sort the order of the instance type results. (options: price)"},
}

// initListTypesCmd initializes the list-types command.
func initListTypesCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list-types",
		Short:   "List available instance types",
		Long:    "Return all the GPU instance types with their corresponding availability and specs.\n\nEvery `availability` entry carries a `rental_type` (`on_demand` or `spot`). Instance types that offer spot list each region twice, once per rental type, and the two entries can differ in `available`. If your integration keys on `region` or checks whether any region is available, filter to `rental_type: on_demand` first to keep the previous behavior. See the [Spot Instances guide](/guides/spotinstances) for details.",
		Example: "  shade instances list-types",
		Args:    cobra.NoArgs,
		RunE:    runListTypesCmd,
		Aliases: []string{"lt"},
		Annotations: map[string]string{
			"speakeasy_operation": "InstancesTypes",
		},
	}
	flagutil.RegisterFlags(cmd, listTypesCmdMeta)
	if err := flagutil.ValidateMeta[operations.InstancesTypesRequest](listTypesCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for list-types: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runListTypesCmd executes the list-types command.
func runListTypesCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	req, err := flagutil.BuildRequest[operations.InstancesTypesRequest](cmd, listTypesCmdMeta, "", "")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Instances.ListTypes(cmd.Context(), req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
