// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package instances

import (
	"fmt"
	"github.com/shadeform/shadeform-cli/internal/client"
	"github.com/shadeform/shadeform-cli/internal/flagutil"
	"github.com/shadeform/shadeform-cli/internal/interactive"
	"github.com/shadeform/shadeform-cli/internal/output"
	"github.com/shadeform/shadeform-cli/internal/sdk"
	"github.com/shadeform/shadeform-cli/internal/sdk/models/operations"
	"github.com/shadeform/shadeform-cli/internal/usage"
	"github.com/spf13/cobra"
)

var restartCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "The instance id [required]"},
}

// initRestartCmd initializes the restart command.
func initRestartCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "restart [id]",
		Short:   "Restart an instance",
		Long:    "Restart an instance. The status of the instance will stay as 'active' throughout, but you may have to wait a few minutes for the instance to be ready to use again.",
		Example: "  shade instances restart --id d290f1ee-6c54-4b01-90e6-d701748f0851",
		Args:    flagutil.PositionalFlagArgs,
		RunE:    runRestartCmd,
		Annotations: map[string]string{
			"speakeasy_operation": "InstancesRestart",
		},
	}
	flagutil.RegisterFlags(cmd, restartCmdMeta)
	if err := flagutil.ValidateMeta[operations.InstancesRestartRequest](restartCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for restart: %w", err)
	}
	if err := flagutil.DeclarePositionalFlag(cmd, "id", "The instance id (or pass it as the [id] argument)", true); err != nil {
		return err
	}
	if err := interactive.Declare(cmd, interactive.CommandSpec{Args: []interactive.ArgSpec{
		{Name: "id", Summary: "The instance id", Required: true, SatisfiedBy: []string{"id"}},
	}}); err != nil {
		return fmt.Errorf("declare interactive arguments for restart: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runRestartCmd executes the restart command.
func runRestartCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if err := flagutil.ResolvePositionalFlag(cmd, args); err != nil {
		return err
	}
	req, err := flagutil.BuildRequest[operations.InstancesRestartRequest](cmd, restartCmdMeta, "", "")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Instances.Restart(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
