// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package instances

import (
	"github.com/shadeform/shadeform-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitInstancesRoot(parent *cobra.Command) error {
	var InstancesCmd = &cobra.Command{
		Use:         "instances",
		Short:       "Create, inspect, update, restart and delete GPU instances",
		Long:        "Create, inspect, update, restart and delete GPU instances.",
		Args:        cobra.NoArgs,
		Annotations: map[string]string{"speakeasy_cli_group": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initListCmd(InstancesCmd); err != nil {
		return err
	}

	if err := initListTypesCmd(InstancesCmd); err != nil {
		return err
	}

	if err := initCreateCmd(InstancesCmd); err != nil {
		return err
	}

	if err := initGetCmd(InstancesCmd); err != nil {
		return err
	}

	if err := initUpdateCmd(InstancesCmd); err != nil {
		return err
	}

	if err := initDeleteCmd(InstancesCmd); err != nil {
		return err
	}

	if err := initRestartCmd(InstancesCmd); err != nil {
		return err
	}

	parent.AddCommand(InstancesCmd)
	return nil
}
