// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package templates

import (
	"github.com/shadeform/shadeform-cli/internal/client"
	"github.com/shadeform/shadeform-cli/internal/output"
	"github.com/shadeform/shadeform-cli/internal/sdk"
	"github.com/shadeform/shadeform-cli/internal/sdk/models/operations"
	"github.com/shadeform/shadeform-cli/internal/usage"
	"github.com/spf13/cobra"
)

// initListFeaturedCmd initializes the list-featured command.
func initListFeaturedCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list-featured",
		Short:   "List featured templates",
		Long:    "List featured templates",
		Example: "  shadeform templates list-featured",
		Args:    cobra.NoArgs,
		RunE:    runListFeaturedCmd,
		Aliases: []string{"lf"},
		Annotations: map[string]string{
			"speakeasy_operation": "TemplatesFeatured",
		},
	}
	parent.AddCommand(cmd)
	return nil
}

// runListFeaturedCmd executes the list-featured command.
func runListFeaturedCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Templates.ListFeatured(cmd.Context(), sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
