// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package templates

import (
	"github.com/shadeform/shadeform-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitTemplatesRoot(parent *cobra.Command) error {
	var TemplatesCmd = &cobra.Command{
		Use:         "templates",
		Short:       "Save and reuse launch configurations as templates",
		Long:        "Save and reuse launch configurations as templates.",
		Args:        cobra.NoArgs,
		Annotations: map[string]string{"speakeasy_cli_group": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initListCmd(TemplatesCmd); err != nil {
		return err
	}

	if err := initListFeaturedCmd(TemplatesCmd); err != nil {
		return err
	}

	if err := initGetCmd(TemplatesCmd); err != nil {
		return err
	}

	if err := initSaveCmd(TemplatesCmd); err != nil {
		return err
	}

	if err := initUpdateCmd(TemplatesCmd); err != nil {
		return err
	}

	if err := initDeleteCmd(TemplatesCmd); err != nil {
		return err
	}

	parent.AddCommand(TemplatesCmd)
	return nil
}
