// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 3b46abbf1667

package templates

import (
	"fmt"
	"github.com/shadeform/shadeform-cli/internal/client"
	"github.com/shadeform/shadeform-cli/internal/flagutil"
	"github.com/shadeform/shadeform-cli/internal/output"
	"github.com/shadeform/shadeform-cli/internal/sdk"
	"github.com/shadeform/shadeform-cli/internal/sdk/models/components"
	"github.com/shadeform/shadeform-cli/internal/sdk/models/operations"
	"github.com/shadeform/shadeform-cli/internal/usage"
	"github.com/spf13/cobra"
)

var saveCmdMeta = []flagutil.FlagMeta{
	{FlagName: "name", FieldPath: "Name", Kind: flagutil.FlagKindString, Required: true, Description: "Name of the template [required]"},
	{FlagName: "description", FieldPath: "Description", Kind: flagutil.FlagKindString, Optional: true, Description: "Description of the template"},
	{FlagName: "public", Shorthand: "p", FieldPath: "Public", Kind: flagutil.FlagKindBool, Optional: true, Description: "Whether the template is publicly available"},
	{FlagName: "launch-configuration", Shorthand: "l", FieldPath: "LaunchConfiguration", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"launch_configuration,omitempty"`, Description: "Defines automatic actions after the instance becomes active."},
	{FlagName: "auto-delete", FieldPath: "AutoDelete", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"auto_delete,omitempty"`, Description: "Set a date or spend threshold to automatically delete the instance"},
	{FlagName: "alert", FieldPath: "Alert", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"alert,omitempty"`, Description: "Set a date or spend threshold to receive an email alert"},
	{FlagName: "volume-mount", Shorthand: "v", FieldPath: "VolumeMount", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"volume_mount,omitempty"`, Description: "Settings for mounting volumes onto file systems"},
	{FlagName: "tags", Shorthand: "t", FieldPath: "Tags", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "Tags associated with the template"},
	{FlagName: "envs", Shorthand: "e", FieldPath: "Envs", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"envs,omitempty"`, Description: "Environment variables for the template (JSON array)"},
	{FlagName: "networking", FieldPath: "Networking", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"networking,omitempty"`, Description: "Network configuration including firewall rules"},
}

// initSaveCmd initializes the save command.
func initSaveCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "save",
		Short:   "Save a template",
		Long:    "Create a new template",
		Example: "  shade templates save --name 'My Template'",
		Args:    cobra.NoArgs,
		RunE:    runSaveCmd,
		Annotations: map[string]string{
			"speakeasy_operation": "TemplatesSave",
		},
	}
	flagutil.RegisterFlags(cmd, saveCmdMeta)
	if err := flagutil.ValidateMeta[components.TemplateSaveRequest](saveCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for save: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin; @path reads a file, @- reads stdin to EOF. Use --schema to print the exact JSON Schema.")
	_ = flagutil.AnnotatePromptFlag(cmd, "body", flagutil.PromptFlagSpec{Kind: "json", BodyFlag: true})
	cmd.Annotations[flagutil.AnnotationWholeBodyFlag] = "body"
	if err := flagutil.AnnotateBodyFields(cmd, saveCmdMeta, "", "body"); err != nil {
		return fmt.Errorf("annotate body fields for save: %w", err)
	}
	cmd.Flags().Bool("schema", false, "Print the exact JSON Schema of the request body and exit")
	_ = flagutil.AnnotatePromptFlag(cmd, "schema", flagutil.PromptFlagSpec{Kind: "bool", DocSurface: true})
	parent.AddCommand(cmd)
	return nil
}

// runSaveCmd executes the save command.
func runSaveCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if requested, _ := cmd.Flags().GetBool("schema"); requested {
		return usage.EmitBodySchema(cmd.OutOrStdout(), "TemplatesSave")
	}
	request, err := flagutil.BuildRequest[components.TemplateSaveRequest](cmd, saveCmdMeta, "", "body")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Templates.Save(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
