// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package templates

import (
	"fmt"
	"github.com/shadeform/shadeform-cli/internal/client"
	"github.com/shadeform/shadeform-cli/internal/flagutil"
	"github.com/shadeform/shadeform-cli/internal/interactive"
	"github.com/shadeform/shadeform-cli/internal/output"
	"github.com/shadeform/shadeform-cli/internal/sdk"
	"github.com/shadeform/shadeform-cli/internal/sdk/models/operations"
	"github.com/shadeform/shadeform-cli/internal/usage"
	"github.com/spf13/cobra"
)

var updateCmdMeta = []flagutil.FlagMeta{
	{FlagName: "template-id", Shorthand: "t", FieldPath: "TemplateID", Kind: flagutil.FlagKindString, Required: true, Description: "The template ID [required]"},
	{FlagName: "name", FieldPath: "Body.Name", Kind: flagutil.FlagKindString, Required: true, Description: "Name of the template [required]"},
	{FlagName: "description", FieldPath: "Body.Description", Kind: flagutil.FlagKindString, Optional: true, Description: "Description of the template"},
	{FlagName: "public", Shorthand: "p", FieldPath: "Body.Public", Kind: flagutil.FlagKindBool, Optional: true, Description: "Whether the template is publicly available"},
	{FlagName: "launch-configuration", Shorthand: "l", FieldPath: "Body.LaunchConfiguration", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"launch_configuration,omitempty"`, Description: "Defines automatic actions after the instance becomes active."},
	{FlagName: "auto-delete", FieldPath: "Body.AutoDelete", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"auto_delete,omitempty"`, Description: "Set a date or spend threshold to automatically delete the instance"},
	{FlagName: "alert", FieldPath: "Body.Alert", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"alert,omitempty"`, Description: "Set a date or spend threshold to receive an email alert"},
	{FlagName: "volume-mount", Shorthand: "v", FieldPath: "Body.VolumeMount", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"volume_mount,omitempty"`, Description: "Settings for mounting volumes onto file systems"},
	{FlagName: "tags", FieldPath: "Body.Tags", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "Tags associated with the template"},
	{FlagName: "envs", Shorthand: "e", FieldPath: "Body.Envs", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"envs,omitempty"`, Description: "Environment variables for the template (JSON array)"},
	{FlagName: "networking", FieldPath: "Body.Networking", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"networking,omitempty"`, Description: "Network configuration including firewall rules"},
}

// initUpdateCmd initializes the update command.
func initUpdateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "update [template-id]",
		Short:   "Update a template",
		Long:    "Update an existing template",
		Example: "  shade templates update --template-id <id> --name 'My Template'",
		Args:    flagutil.PositionalFlagArgs,
		RunE:    runUpdateCmd,
		Annotations: map[string]string{
			"speakeasy_operation": "TemplatesUpdate",
		},
	}
	flagutil.RegisterFlags(cmd, updateCmdMeta)
	if err := flagutil.ValidateMeta[operations.TemplatesUpdateRequest](updateCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for update: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin; @path reads a file, @- reads stdin to EOF. Use --schema to print the exact JSON Schema.")
	_ = flagutil.AnnotatePromptFlag(cmd, "body", flagutil.PromptFlagSpec{Kind: "json", BodyFlag: true})
	cmd.Annotations[flagutil.AnnotationWholeBodyFlag] = "body"
	if err := flagutil.AnnotateBodyFields(cmd, updateCmdMeta, "Body", "body"); err != nil {
		return fmt.Errorf("annotate body fields for update: %w", err)
	}
	cmd.Flags().Bool("schema", false, "Print the exact JSON Schema of the request body and exit")
	_ = flagutil.AnnotatePromptFlag(cmd, "schema", flagutil.PromptFlagSpec{Kind: "bool", DocSurface: true})
	if err := flagutil.DeclarePositionalFlag(cmd, "template-id", "The template ID (or pass it as the [template-id] argument)", true); err != nil {
		return err
	}
	if err := interactive.Declare(cmd, interactive.CommandSpec{Args: []interactive.ArgSpec{
		{Name: "template-id", Summary: "The template ID", Required: true, SatisfiedBy: []string{"template-id"}},
	}}); err != nil {
		return fmt.Errorf("declare interactive arguments for update: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runUpdateCmd executes the update command.
func runUpdateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if requested, _ := cmd.Flags().GetBool("schema"); requested {
		return usage.EmitBodySchema(cmd.OutOrStdout(), "TemplatesUpdate")
	}
	if err := flagutil.ResolvePositionalFlag(cmd, args); err != nil {
		return err
	}
	req, err := flagutil.BuildRequest[operations.TemplatesUpdateRequest](cmd, updateCmdMeta, "Body", "body")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Templates.Update(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
