workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Shadeform API:
        inputs:
            - location: https://docs.shadeform.ai/openapi.yaml
        overlays:
            - location: .speakeasy/overlay.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/shadeform-ivx/production/shadeform-api
targets:
    shadeform:
        target: cli
        source: Shadeform API
