// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package clusters

import (
	"fmt"
	"github.com/shadeform/shadeform-cli/internal/client"
	"github.com/shadeform/shadeform-cli/internal/flagutil"
	"github.com/shadeform/shadeform-cli/internal/output"
	"github.com/shadeform/shadeform-cli/internal/sdk"
	"github.com/shadeform/shadeform-cli/internal/sdk/models/components"
	"github.com/shadeform/shadeform-cli/internal/sdk/models/operations"
	"github.com/shadeform/shadeform-cli/internal/usage"
	"github.com/spf13/cobra"
)

var createCmdMeta = []flagutil.FlagMeta{
	{FlagName: "name", FieldPath: "Name", Kind: flagutil.FlagKindString, Required: true, Description: "The name of the cluster. [required]"},
	{FlagName: "cloud", FieldPath: "Cloud", Kind: flagutil.FlagKindString, Required: true, Description: "The cloud provider for the cluster. [required]"},
	{FlagName: "region", Shorthand: "r", FieldPath: "Region", Kind: flagutil.FlagKindString, Required: true, Description: "The region where the cluster will be deployed. [required]"},
	{FlagName: "cluster-type", FieldPath: "ClusterType", Kind: flagutil.FlagKindString, Required: true, Description: "The type of GPU cluster to create. [required]"},
	{FlagName: "num-instances", FieldPath: "NumInstances", Kind: flagutil.FlagKindInt64, Required: true, Description: "The number of instances in the cluster. [required]"},
	{FlagName: "ssh-key-id", Shorthand: "s", FieldPath: "SSHKeyID", Kind: flagutil.FlagKindString, Optional: true, Description: "The SSH key ID to use for the cluster instances."},
	{FlagName: "os", FieldPath: "Os", Kind: flagutil.FlagKindString, Optional: true, Description: "The operating system for the cluster."},
}

// initCreateCmd initializes the create command.
func initCreateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "create",
		Short:   "Create a cluster",
		Long:    "Create a new GPU cluster.",
		Example: "  shade clusters create --name protestant-aquamarine-cluster --cloud denvr --region houston-usa-1 --cluster-type H100_sxm5x8 --num-instances 2",
		Args:    cobra.NoArgs,
		RunE:    runCreateCmd,
		Annotations: map[string]string{
			"speakeasy_operation": "ClustersCreate",
		},
	}
	flagutil.RegisterFlags(cmd, createCmdMeta)
	if err := flagutil.ValidateMeta[components.CreateClusterRequest](createCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for create: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin; @path reads a file, @- reads stdin to EOF. Use --schema to print the exact JSON Schema.")
	_ = flagutil.AnnotatePromptFlag(cmd, "body", flagutil.PromptFlagSpec{Kind: "json", BodyFlag: true})
	cmd.Annotations[flagutil.AnnotationWholeBodyFlag] = "body"
	if err := flagutil.AnnotateBodyFields(cmd, createCmdMeta, "", "body"); err != nil {
		return fmt.Errorf("annotate body fields for create: %w", err)
	}
	cmd.Flags().Bool("schema", false, "Print the exact JSON Schema of the request body and exit")
	_ = flagutil.AnnotatePromptFlag(cmd, "schema", flagutil.PromptFlagSpec{Kind: "bool", DocSurface: true})
	parent.AddCommand(cmd)
	return nil
}

// runCreateCmd executes the create command.
func runCreateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if requested, _ := cmd.Flags().GetBool("schema"); requested {
		return usage.EmitBodySchema(cmd.OutOrStdout(), "ClustersCreate")
	}
	request, err := flagutil.BuildRequest[components.CreateClusterRequest](cmd, createCmdMeta, "", "body")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Clusters.Create(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
