// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package clusters

import (
	"fmt"
	"github.com/shadeform/shadeform-cli/internal/client"
	"github.com/shadeform/shadeform-cli/internal/flagutil"
	"github.com/shadeform/shadeform-cli/internal/interactive"
	"github.com/shadeform/shadeform-cli/internal/output"
	"github.com/shadeform/shadeform-cli/internal/sdk"
	"github.com/shadeform/shadeform-cli/internal/sdk/models/operations"
	"github.com/shadeform/shadeform-cli/internal/usage"
	"github.com/spf13/cobra"
)

var getCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "The cluster id [required]"},
}

// initGetCmd initializes the get command.
func initGetCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get [id]",
		Short:   "Get a cluster",
		Long:    "Get details for the specified, non deleted, cluster in the url.",
		Example: "  shadeform clusters get --id 8eda86fe-0f36-41ed-9837-0ccf8f6e0fcb",
		Args:    flagutil.PositionalFlagArgs,
		RunE:    runGetCmd,
		Annotations: map[string]string{
			"speakeasy_operation": "ClustersInfo",
		},
	}
	flagutil.RegisterFlags(cmd, getCmdMeta)
	if err := flagutil.ValidateMeta[operations.ClustersInfoRequest](getCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get: %w", err)
	}
	if err := flagutil.DeclarePositionalFlag(cmd, "id", "The cluster id (or pass it as the [id] argument)", true); err != nil {
		return err
	}
	if err := interactive.Declare(cmd, interactive.CommandSpec{Args: []interactive.ArgSpec{
		{Name: "id", Summary: "The cluster id", Required: true, SatisfiedBy: []string{"id"}},
	}}); err != nil {
		return fmt.Errorf("declare interactive arguments for get: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetCmd executes the get command.
func runGetCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if err := flagutil.ResolvePositionalFlag(cmd, args); err != nil {
		return err
	}
	req, err := flagutil.BuildRequest[operations.ClustersInfoRequest](cmd, getCmdMeta, "", "")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Clusters.Get(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
