// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package clusters

import (
	"github.com/shadeform/shadeform-cli/internal/client"
	"github.com/shadeform/shadeform-cli/internal/output"
	"github.com/shadeform/shadeform-cli/internal/sdk"
	"github.com/shadeform/shadeform-cli/internal/sdk/models/operations"
	"github.com/shadeform/shadeform-cli/internal/usage"
	"github.com/spf13/cobra"
)

// initListTypesCmd initializes the list-types command.
func initListTypesCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list-types",
		Short:   "List available cluster types",
		Long:    "Return all the GPU cluster types with their corresponding availability and specs.",
		Example: "  shade clusters list-types",
		Args:    cobra.NoArgs,
		RunE:    runListTypesCmd,
		Aliases: []string{"lt"},
		Annotations: map[string]string{
			"speakeasy_operation": "ClustersTypes",
		},
	}
	parent.AddCommand(cmd)
	return nil
}

// runListTypesCmd executes the list-types command.
func runListTypesCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Clusters.ListTypes(cmd.Context(), sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
