// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: f966de12bdf0

package clusters

import (
	"github.com/shadeform/shadeform-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitClustersRoot(parent *cobra.Command) error {
	var ClustersCmd = &cobra.Command{
		Use:         "clusters",
		Short:       "Create, inspect and delete multi-node GPU clusters",
		Long:        "Create, inspect and delete multi-node GPU clusters.",
		Args:        cobra.NoArgs,
		Annotations: map[string]string{"speakeasy_cli_group": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initListCmd(ClustersCmd); err != nil {
		return err
	}

	if err := initListTypesCmd(ClustersCmd); err != nil {
		return err
	}

	if err := initCreateCmd(ClustersCmd); err != nil {
		return err
	}

	if err := initGetCmd(ClustersCmd); err != nil {
		return err
	}

	if err := initDeleteCmd(ClustersCmd); err != nil {
		return err
	}

	parent.AddCommand(ClustersCmd)
	return nil
}
