// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AddSSHKeyResponse struct {
	// The ID of the SSH Key.
	ID string `json:"id"`
}

func (a *AddSSHKeyResponse) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}
