// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 9a4cdaee66e0

package components

type AddSSHKeyRequest struct {
	// The name of the SSH Key.
	Name string `json:"name"`
	// The public key.
	PublicKey string `json:"public_key"`
}

func (a *AddSSHKeyRequest) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AddSSHKeyRequest) GetPublicKey() string {
	if a == nil {
		return ""
	}
	return a.PublicKey
}
