// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Alert - Set a date or spend threshold to receive an email alert
type Alert struct {
	// RFC3339 date string
	DateThreshold *string `json:"date_threshold,omitzero"`
	// Valid decimal representation of a dollar amount
	SpendThreshold *string `json:"spend_threshold,omitzero"`
}

func (a *Alert) GetDateThreshold() *string {
	if a == nil {
		return nil
	}
	return a.DateThreshold
}

func (a *Alert) GetSpendThreshold() *string {
	if a == nil {
		return nil
	}
	return a.SpendThreshold
}
