// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 51706c63946e

package components

// AutoDelete - Set a date or spend threshold to automatically delete the instance
type AutoDelete struct {
	// RFC3339 date string
	DateThreshold *string `json:"date_threshold,omitzero"`
	// Valid decimal representation of a dollar amount
	SpendThreshold *string `json:"spend_threshold,omitzero"`
}

func (a *AutoDelete) GetDateThreshold() *string {
	if a == nil {
		return nil
	}
	return a.DateThreshold
}

func (a *AutoDelete) GetSpendThreshold() *string {
	if a == nil {
		return nil
	}
	return a.SpendThreshold
}
