// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AvailabilityRentalType - The rental type this entry describes. Regular entries are tagged `on_demand`; an instance type that offers spot lists a second entry per region tagged `spot` with its own `available` verdict and `hourly_price`. Filter by `rental_type` rather than assuming one entry per region.
type AvailabilityRentalType string

const (
	AvailabilityRentalTypeOnDemand AvailabilityRentalType = "on_demand"
	AvailabilityRentalTypeSpot     AvailabilityRentalType = "spot"
)

func (e AvailabilityRentalType) ToPointer() *AvailabilityRentalType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AvailabilityRentalType) IsExact() bool {
	if e != nil {
		switch *e {
		case "on_demand", "spot":
			return true
		}
	}
	return false
}

type Availability struct {
	// Specifies the region.
	Region string `json:"region"`
	// Indicate whether the instance is available in the region.
	Available bool `json:"available"`
	// The display name of the region
	DisplayName string `json:"display_name"`
	// The rental type this entry describes. Regular entries are tagged `on_demand`; an instance type that offers spot lists a second entry per region tagged `spot` with its own `available` verdict and `hourly_price`. Filter by `rental_type` rather than assuming one entry per region.
	RentalType AvailabilityRentalType `json:"rental_type"`
	// The spot hourly price as a decimal string in dollars. Only present on spot availability entries.
	HourlyPrice *string `json:"hourly_price,omitzero"`
}

func (a *Availability) GetRegion() string {
	if a == nil {
		return ""
	}
	return a.Region
}

func (a *Availability) GetAvailable() bool {
	if a == nil {
		return false
	}
	return a.Available
}

func (a *Availability) GetDisplayName() string {
	if a == nil {
		return ""
	}
	return a.DisplayName
}

func (a *Availability) GetRentalType() AvailabilityRentalType {
	if a == nil {
		return AvailabilityRentalType("")
	}
	return a.RentalType
}

func (a *Availability) GetHourlyPrice() *string {
	if a == nil {
		return nil
	}
	return a.HourlyPrice
}
