// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BootTime struct {
	// boot time minimum estimate
	MinBootInSec *int64 `json:"min_boot_in_sec,omitzero"`
	// boot time maximum estimate
	MaxBootInSec *int64 `json:"max_boot_in_sec,omitzero"`
}

func (b *BootTime) GetMinBootInSec() *int64 {
	if b == nil {
		return nil
	}
	return b.MinBootInSec
}

func (b *BootTime) GetMaxBootInSec() *int64 {
	if b == nil {
		return nil
	}
	return b.MaxBootInSec
}
