// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 09eaf096e7fc

package components

type ClusterTypesResponse struct {
	ClusterTypes []ClusterType `json:"cluster_types"`
}

func (c *ClusterTypesResponse) GetClusterTypes() []ClusterType {
	if c == nil {
		return []ClusterType{}
	}
	return c.ClusterTypes
}
