// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ClusterAvailability struct {
	// The region code.
	Region string `json:"region"`
	// Human-readable display name for the region.
	DisplayName string `json:"display_name"`
	// Whether the cluster type is available in this region.
	Available bool `json:"available"`
}

func (c *ClusterAvailability) GetRegion() string {
	if c == nil {
		return ""
	}
	return c.Region
}

func (c *ClusterAvailability) GetDisplayName() string {
	if c == nil {
		return ""
	}
	return c.DisplayName
}

func (c *ClusterAvailability) GetAvailable() bool {
	if c == nil {
		return false
	}
	return c.Available
}
