// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c7f70d33a7bf

package components

type ClusterRegionInfo struct {
	// The region code.
	Region string `json:"region"`
	// Human-readable display name for the region.
	DisplayName string `json:"display_name"`
}

func (c *ClusterRegionInfo) GetRegion() string {
	if c == nil {
		return ""
	}
	return c.Region
}

func (c *ClusterRegionInfo) GetDisplayName() string {
	if c == nil {
		return ""
	}
	return c.DisplayName
}
