// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 1b6e8d1d2fc5

package components

type ClustersResponse struct {
	Clusters []Cluster `json:"clusters"`
}

func (c *ClustersResponse) GetClusters() []Cluster {
	if c == nil {
		return []Cluster{}
	}
	return c.Clusters
}
