// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 0cad7bf30b0f

package components

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/optionalnullable"
	"github.com/shadeform/shadeform-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type Cluster struct {
	// The unique identifier for the cluster.
	ID string `json:"id"`
	// The cloud provider for the cluster.
	Cloud string `json:"cloud"`
	// The name of the cluster.
	Name string `json:"name"`
	// The cloud provider assigned cluster ID.
	CloudClusterID optionalnullable.OptionalNullable[string] `json:"cloud_cluster_id,omitzero"`
	RegionInfo     ClusterRegionInfo                         `json:"region_info"`
	// The current status of the cluster.
	Status string `json:"status"`
	// Additional details about the cluster status.
	StatusDetails optionalnullable.OptionalNullable[string] `json:"status_details,omitzero"`
	// The timestamp when the cluster was created.
	CreatedAt time.Time `json:"created_at"`
	// The timestamp when the cluster was last updated.
	UpdatedAt time.Time `json:"updated_at"`
	// Array of instances in the cluster.
	Instances []Instance `json:"instances"`
	// The hourly price of the cluster in cents.
	HourlyPrice int64 `json:"hourly_price"`
	// Estimated cost of the cluster.
	CostEstimate optionalnullable.OptionalNullable[string] `json:"cost_estimate,omitzero"`
	// The timestamp when the cluster became active.
	ActiveAt optionalnullable.OptionalNullable[time.Time] `json:"active_at,omitzero"`
}

func (c Cluster) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Cluster) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *Cluster) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *Cluster) GetCloud() string {
	if c == nil {
		return ""
	}
	return c.Cloud
}

func (c *Cluster) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *Cluster) GetCloudClusterID() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.CloudClusterID
}

func (c *Cluster) GetRegionInfo() ClusterRegionInfo {
	if c == nil {
		return ClusterRegionInfo{}
	}
	return c.RegionInfo
}

func (c *Cluster) GetStatus() string {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *Cluster) GetStatusDetails() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.StatusDetails
}

func (c *Cluster) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *Cluster) GetUpdatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.UpdatedAt
}

func (c *Cluster) GetInstances() []Instance {
	if c == nil {
		return []Instance{}
	}
	return c.Instances
}

func (c *Cluster) GetHourlyPrice() int64 {
	if c == nil {
		return 0
	}
	return c.HourlyPrice
}

func (c *Cluster) GetCostEstimate() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.CostEstimate
}

func (c *Cluster) GetActiveAt() optionalnullable.OptionalNullable[time.Time] {
	if c == nil {
		return nil
	}
	return c.ActiveAt
}
