// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ClusterType struct {
	// The cloud provider.
	Cloud string `json:"cloud"`
	// The number of instances in this cluster type.
	NumInstances int64               `json:"num_instances"`
	Availability ClusterAvailability `json:"availability"`
	// Information about a specific instance type
	ClusterType InstanceType `json:"cluster_type"`
}

func (c *ClusterType) GetCloud() string {
	if c == nil {
		return ""
	}
	return c.Cloud
}

func (c *ClusterType) GetNumInstances() int64 {
	if c == nil {
		return 0
	}
	return c.NumInstances
}

func (c *ClusterType) GetAvailability() ClusterAvailability {
	if c == nil {
		return ClusterAvailability{}
	}
	return c.Availability
}

func (c *ClusterType) GetClusterType() InstanceType {
	if c == nil {
		return InstanceType{}
	}
	return c.ClusterType
}
