// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateVolumeResponse struct {
	// The ID of the storage volume.
	ID string `json:"id"`
}

func (c *CreateVolumeResponse) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}
