// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c391848086e8

package components

// CreateClusterResponse - Response of the /clusters/create API call
type CreateClusterResponse struct {
	// The unique identifier for the newly created cluster.
	ID string `json:"id"`
}

func (c *CreateClusterResponse) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}
