// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 06c25e0cc7e7

package components

type CreateClusterRequest struct {
	// The name of the cluster.
	Name string `json:"name"`
	// The cloud provider for the cluster.
	Cloud string `json:"cloud"`
	// The region where the cluster will be deployed.
	Region string `json:"region"`
	// The type of GPU cluster to create.
	ClusterType string `json:"cluster_type"`
	// The number of instances in the cluster.
	NumInstances int64 `json:"num_instances"`
	// The SSH key ID to use for the cluster instances.
	SSHKeyID *string `json:"ssh_key_id,omitzero"`
	// The operating system for the cluster.
	Os *string `json:"os,omitzero"`
}

func (c *CreateClusterRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateClusterRequest) GetCloud() string {
	if c == nil {
		return ""
	}
	return c.Cloud
}

func (c *CreateClusterRequest) GetRegion() string {
	if c == nil {
		return ""
	}
	return c.Region
}

func (c *CreateClusterRequest) GetClusterType() string {
	if c == nil {
		return ""
	}
	return c.ClusterType
}

func (c *CreateClusterRequest) GetNumInstances() int64 {
	if c == nil {
		return 0
	}
	return c.NumInstances
}

func (c *CreateClusterRequest) GetSSHKeyID() *string {
	if c == nil {
		return nil
	}
	return c.SSHKeyID
}

func (c *CreateClusterRequest) GetOs() *string {
	if c == nil {
		return nil
	}
	return c.Os
}
