// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d3e4cb8adedd

package components

// CreateResponse - Response of the /instances/create API call
type CreateResponse struct {
	// The unique identifier for the instance. Used in the instances for the /instances/{id}/info and /instances/{id}/delete APIs.
	ID string `json:"id"`
}

func (c *CreateResponse) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}
