// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateVolumeRequest struct {
	// Specifies the underlying cloud provider. See this [explanation](/getting-started/concepts#cloud-cloud-provider) for more details.
	Cloud string `json:"cloud"`
	// Specifies the region.
	Region string `json:"region"`
	// Storage volume size in GB
	SizeInGb int64 `json:"size_in_gb"`
	// The name of the storage volume.
	Name string `json:"name"`
}

func (c *CreateVolumeRequest) GetCloud() string {
	if c == nil {
		return ""
	}
	return c.Cloud
}

func (c *CreateVolumeRequest) GetRegion() string {
	if c == nil {
		return ""
	}
	return c.Region
}

func (c *CreateVolumeRequest) GetSizeInGb() int64 {
	if c == nil {
		return 0
	}
	return c.SizeInGb
}

func (c *CreateVolumeRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}
