// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/shadeform/shadeform-cli/internal/sdk/sdkinternal/utils"
)

// CreateRequestRentalType - How the instance is rented. Defaults to on_demand. Spot instances run at a discounted hourly price but are interruptible: Shadeform may reclaim the capacity at any time, at which point the instance is terminated. Spot requires an instance type that supports it (see the availability entries tagged rental_type spot in the instance types response) and shade_cloud set to true.
type CreateRequestRentalType string

const (
	CreateRequestRentalTypeOnDemand CreateRequestRentalType = "on_demand"
	CreateRequestRentalTypeSpot     CreateRequestRentalType = "spot"
)

func (e CreateRequestRentalType) ToPointer() *CreateRequestRentalType {
	return &e
}
func (e *CreateRequestRentalType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "on_demand":
		fallthrough
	case "spot":
		*e = CreateRequestRentalType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateRequestRentalType: %v", v)
	}
}

type CreateRequest struct {
	// Specifies the underlying cloud provider. See this [explanation](/getting-started/concepts#cloud-cloud-provider) for more details.
	Cloud string `json:"cloud"`
	// Specifies the region.
	Region string `json:"region"`
	// The Shadeform standardized instance type. See this [explanation](/getting-started/concepts#shade-instance-type-and-cloud-instance-type) for more details.
	ShadeInstanceType string `json:"shade_instance_type"`
	// Specifies if the instance is launched in [Shade Cloud](/getting-started/concepts#shade-cloud) or in a linked cloud account.
	ShadeCloud bool `json:"shade_cloud"`
	// The name of the instance
	Name string `json:"name"`
	// How the instance is rented. Defaults to on_demand. Spot instances run at a discounted hourly price but are interruptible: Shadeform may reclaim the capacity at any time, at which point the instance is terminated. Spot requires an instance type that supports it (see the availability entries tagged rental_type spot in the instance types response) and shade_cloud set to true.
	RentalType *CreateRequestRentalType `default:"on_demand" json:"rental_type"`
	// The operating system of the instance.
	Os *string `json:"os,omitzero"`
	// The ID of the template to use for this instance
	TemplateID *string `json:"template_id,omitzero"`
	// Defines automatic actions after the instance becomes active.
	LaunchConfiguration *LaunchConfiguration `json:"launch_configuration,omitzero"`
	// List of volume IDs to be mounted. Currently only supports 1 volume at a time.
	VolumeIds []string `json:"volume_ids,omitzero"`
	// The ID of the SSH Key.
	SSHKeyID *string `json:"ssh_key_id,omitzero"`
	// Set a date or spend threshold to automatically delete the instance
	AutoDelete *AutoDelete `json:"auto_delete,omitzero"`
	// Set a date or spend threshold to receive an email alert
	Alert *Alert `json:"alert,omitzero"`
	// Settings for mounting volumes onto file systems
	VolumeMount *VolumeMount `json:"volume_mount,omitzero"`
	// Add custom, searchable tags to instances.
	Tags []string `json:"tags,omitzero"`
	// List of environment variable name and values to automatically add to the instance
	Envs []Env `json:"envs,omitzero"`
}

func (c CreateRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateRequest) GetCloud() string {
	if c == nil {
		return ""
	}
	return c.Cloud
}

func (c *CreateRequest) GetRegion() string {
	if c == nil {
		return ""
	}
	return c.Region
}

func (c *CreateRequest) GetShadeInstanceType() string {
	if c == nil {
		return ""
	}
	return c.ShadeInstanceType
}

func (c *CreateRequest) GetShadeCloud() bool {
	if c == nil {
		return false
	}
	return c.ShadeCloud
}

func (c *CreateRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateRequest) GetRentalType() *CreateRequestRentalType {
	if c == nil {
		return nil
	}
	return c.RentalType
}

func (c *CreateRequest) GetOs() *string {
	if c == nil {
		return nil
	}
	return c.Os
}

func (c *CreateRequest) GetTemplateID() *string {
	if c == nil {
		return nil
	}
	return c.TemplateID
}

func (c *CreateRequest) GetLaunchConfiguration() *LaunchConfiguration {
	if c == nil {
		return nil
	}
	return c.LaunchConfiguration
}

func (c *CreateRequest) GetVolumeIds() []string {
	if c == nil {
		return nil
	}
	return c.VolumeIds
}

func (c *CreateRequest) GetSSHKeyID() *string {
	if c == nil {
		return nil
	}
	return c.SSHKeyID
}

func (c *CreateRequest) GetAutoDelete() *AutoDelete {
	if c == nil {
		return nil
	}
	return c.AutoDelete
}

func (c *CreateRequest) GetAlert() *Alert {
	if c == nil {
		return nil
	}
	return c.Alert
}

func (c *CreateRequest) GetVolumeMount() *VolumeMount {
	if c == nil {
		return nil
	}
	return c.VolumeMount
}

func (c *CreateRequest) GetTags() []string {
	if c == nil {
		return nil
	}
	return c.Tags
}

func (c *CreateRequest) GetEnvs() []Env {
	if c == nil {
		return nil
	}
	return c.Envs
}
