// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/sdkinternal/utils"
)

// DockerConfiguration - May only be used if launch_configuration.type is 'docker'. Use docker_configuration to automatically pull and run a docker image. See this [tutorial](/guides/dockercontainers) for examples.
type DockerConfiguration struct {
	// Specifies the docker image to be pulled and run on the instance at startup.
	Image string `json:"image"`
	// Specifies the container arguments passed into the image at runtime.
	Args *string `json:"args,omitzero"`
	// Describes the amount of shared memory allocated for the container. Equivalent to using the --shm-size flag in the docker cli. If shared_memory_in_gb is not specified, then the container will use the host namespace which is the equivalent of --ipc=host.
	SharedMemoryInGb *int64 `json:"shared_memory_in_gb,omitzero"`
	// List of environment variable name-value pairs that will be passed to the docker container.
	Envs []Env `json:"envs,omitzero"`
	// List of port mappings between the host instance and the docker container. Equivalent of -p flag for docker run command.
	PortMappings []PortMappings `json:"port_mappings,omitzero"`
	// List of volume mounts between the host instance and the docker container. Equivalent of -v flag for docker run command.
	VolumeMounts        []VolumeMounts       `json:"volume_mounts,omitzero"`
	RegistryCredentials *RegistryCredentials `json:"registry_credentials,omitzero"`
}

func (d DockerConfiguration) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DockerConfiguration) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DockerConfiguration) GetImage() string {
	if d == nil {
		return ""
	}
	return d.Image
}

func (d *DockerConfiguration) GetArgs() *string {
	if d == nil {
		return nil
	}
	return d.Args
}

func (d *DockerConfiguration) GetSharedMemoryInGb() *int64 {
	if d == nil {
		return nil
	}
	return d.SharedMemoryInGb
}

func (d *DockerConfiguration) GetEnvs() []Env {
	if d == nil {
		return nil
	}
	return d.Envs
}

func (d *DockerConfiguration) GetPortMappings() []PortMappings {
	if d == nil {
		return nil
	}
	return d.PortMappings
}

func (d *DockerConfiguration) GetVolumeMounts() []VolumeMounts {
	if d == nil {
		return nil
	}
	return d.VolumeMounts
}

func (d *DockerConfiguration) GetRegistryCredentials() *RegistryCredentials {
	if d == nil {
		return nil
	}
	return d.RegistryCredentials
}
