// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 4250c0d7a98c

package components

// Env - Environment variables for the container image.
type Env struct {
	// Name of the environment variable
	Name string `json:"name"`
	// Value of the environment variable
	Value string `json:"value"`
}

func (e *Env) GetName() string {
	if e == nil {
		return ""
	}
	return e.Name
}

func (e *Env) GetValue() string {
	if e == nil {
		return ""
	}
	return e.Value
}
