// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 160b80056512

package components

type InstancesResponse struct {
	Instances []Instance `json:"instances"`
}

func (i *InstancesResponse) GetInstances() []Instance {
	if i == nil {
		return []Instance{}
	}
	return i.Instances
}
