// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type InstancesResponse struct {
	Instances []Instance `json:"instances"`
}

func (i *InstancesResponse) GetInstances() []Instance {
	if i == nil {
		return []Instance{}
	}
	return i.Instances
}
