// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// InstancePortMappings - List of port mappings on an instance that a Cloud Provider might have automatically set up.
type InstancePortMappings struct {
	InternalPort *int64 `json:"internal_port,omitzero"`
	ExternalPort *int64 `json:"external_port,omitzero"`
}

func (i *InstancePortMappings) GetInternalPort() *int64 {
	if i == nil {
		return nil
	}
	return i.InternalPort
}

func (i *InstancePortMappings) GetExternalPort() *int64 {
	if i == nil {
		return nil
	}
	return i.ExternalPort
}
