// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type InstanceTypeConfiguration struct {
	// The amount of memory for the instance in gigabytes. Note that this is not VRAM which is determined by GPU type and the number of GPUs.
	MemoryInGb int64 `json:"memory_in_gb"`
	// The amount of storage for the instance. If this storage is too low for the instance type, please email support@shadeform.ai as the storage may be adjustable.
	StorageInGb int64 `json:"storage_in_gb"`
	// The number of vCPUs for the instance.
	Vcpus int64 `json:"vcpus"`
	// The number of GPUs for the instance.
	NumGpus int64 `json:"num_gpus"`
	// The type of GPU for the instance.
	GpuType string `json:"gpu_type"`
	// The type of GPU interconnect.
	Interconnect string `json:"interconnect"`
	// If the instance has NVLink
	Nvlink *bool `json:"nvlink,omitzero"`
	// The video memory per GPU for the instance in gigabytes.
	VramPerGpuInGb int64 `json:"vram_per_gpu_in_gb"`
	// The list of available operating systems for the instance.
	OsOptions []string `json:"os_options"`
	// The manufacturer of the gpu
	GpuManufacturer string `json:"gpu_manufacturer"`
}

func (i *InstanceTypeConfiguration) GetMemoryInGb() int64 {
	if i == nil {
		return 0
	}
	return i.MemoryInGb
}

func (i *InstanceTypeConfiguration) GetStorageInGb() int64 {
	if i == nil {
		return 0
	}
	return i.StorageInGb
}

func (i *InstanceTypeConfiguration) GetVcpus() int64 {
	if i == nil {
		return 0
	}
	return i.Vcpus
}

func (i *InstanceTypeConfiguration) GetNumGpus() int64 {
	if i == nil {
		return 0
	}
	return i.NumGpus
}

func (i *InstanceTypeConfiguration) GetGpuType() string {
	if i == nil {
		return ""
	}
	return i.GpuType
}

func (i *InstanceTypeConfiguration) GetInterconnect() string {
	if i == nil {
		return ""
	}
	return i.Interconnect
}

func (i *InstanceTypeConfiguration) GetNvlink() *bool {
	if i == nil {
		return nil
	}
	return i.Nvlink
}

func (i *InstanceTypeConfiguration) GetVramPerGpuInGb() int64 {
	if i == nil {
		return 0
	}
	return i.VramPerGpuInGb
}

func (i *InstanceTypeConfiguration) GetOsOptions() []string {
	if i == nil {
		return []string{}
	}
	return i.OsOptions
}

func (i *InstanceTypeConfiguration) GetGpuManufacturer() string {
	if i == nil {
		return ""
	}
	return i.GpuManufacturer
}
