// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 05f5b816a843

package components

// InstanceTypesResponse - Response of /instances/types
type InstanceTypesResponse struct {
	InstanceTypes []InstanceType `json:"instance_types"`
}

func (i *InstanceTypesResponse) GetInstanceTypes() []InstanceType {
	if i == nil {
		return []InstanceType{}
	}
	return i.InstanceTypes
}
