// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: bc81e19f788c

package components

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type InstanceConfiguration struct {
	// The amount of memory for the instance in gigabytes. Note that this is not VRAM which is determined by GPU type and the number of GPUs.
	MemoryInGb int64 `json:"memory_in_gb"`
	// The amount of storage for the instance. If this storage is too low for the instance type, please email support@shadeform.ai as the storage may be adjustable.
	StorageInGb int64 `json:"storage_in_gb"`
	// The number of vCPUs for the instance.
	Vcpus int64 `json:"vcpus"`
	// The number of GPUs for the instance.
	NumGpus int64 `json:"num_gpus"`
	// The type of GPU for the instance.
	GpuType string `json:"gpu_type"`
	// The type of GPU interconnect.
	Interconnect string `json:"interconnect"`
	// If the instance has NVLink
	Nvlink *bool `json:"nvlink,omitzero"`
	// The video memory per GPU for the instance in gigabytes.
	VramPerGpuInGb int64 `json:"vram_per_gpu_in_gb"`
	// The manufacturer of the gpu
	GpuManufacturer string `json:"gpu_manufacturer"`
	// The operating system of the instance.
	Os string `json:"os"`
}

func (i *InstanceConfiguration) GetMemoryInGb() int64 {
	if i == nil {
		return 0
	}
	return i.MemoryInGb
}

func (i *InstanceConfiguration) GetStorageInGb() int64 {
	if i == nil {
		return 0
	}
	return i.StorageInGb
}

func (i *InstanceConfiguration) GetVcpus() int64 {
	if i == nil {
		return 0
	}
	return i.Vcpus
}

func (i *InstanceConfiguration) GetNumGpus() int64 {
	if i == nil {
		return 0
	}
	return i.NumGpus
}

func (i *InstanceConfiguration) GetGpuType() string {
	if i == nil {
		return ""
	}
	return i.GpuType
}

func (i *InstanceConfiguration) GetInterconnect() string {
	if i == nil {
		return ""
	}
	return i.Interconnect
}

func (i *InstanceConfiguration) GetNvlink() *bool {
	if i == nil {
		return nil
	}
	return i.Nvlink
}

func (i *InstanceConfiguration) GetVramPerGpuInGb() int64 {
	if i == nil {
		return 0
	}
	return i.VramPerGpuInGb
}

func (i *InstanceConfiguration) GetGpuManufacturer() string {
	if i == nil {
		return ""
	}
	return i.GpuManufacturer
}

func (i *InstanceConfiguration) GetOs() string {
	if i == nil {
		return ""
	}
	return i.Os
}

type Instance struct {
	// The unique identifier for the instance. Used in the instances for the /instances/{id}/info and /instances/{id}/delete APIs.
	ID string `json:"id"`
	// Specifies the underlying cloud provider. See this [explanation](/getting-started/concepts#cloud-cloud-provider) for more details.
	Cloud string `json:"cloud"`
	// Specifies the region.
	Region string `json:"region"`
	// The Shadeform standardized instance type. See this [explanation](/getting-started/concepts#shade-instance-type-and-cloud-instance-type) for more details.
	ShadeInstanceType string `json:"shade_instance_type"`
	// The instance type for the underlying cloud provider. See this [explanation](/getting-started/concepts#shade-instance-type-and-cloud-instance-type) for more details.
	CloudInstanceType string `json:"cloud_instance_type"`
	// The unique identifier of the instance issued by the underlying cloud provider.
	CloudAssignedID string `json:"cloud_assigned_id"`
	// Specifies if the instance is launched in [Shade Cloud](/getting-started/concepts#shade-cloud) or in a linked cloud account.
	ShadeCloud bool `json:"shade_cloud"`
	// The name of the instance
	Name          string                `json:"name"`
	Configuration InstanceConfiguration `json:"configuration"`
	// The public IP address of the instance. In select cases, it may also be the DNS.
	IP string `json:"ip"`
	// The SSH user used to SSH into the instance.
	SSHUser string `json:"ssh_user"`
	// The SSH port of the instance. In most cases, this will be port 22 but for some clouds, this may be a different port.
	SSHPort int64 `json:"ssh_port"`
	// The status of the instance.
	Status Status `json:"status"`
	// Additional context for the status. A spot instance that was reclaimed by Shadeform (rather than deleted by you) carries the value "preempted" once terminated.
	StatusDetails *string `json:"status_details,omitzero"`
	// The cost incurred by the instance. This only the cost via Shadeform. If the instance is deployed in your own cloud account, then all billing is through your cloud provider.
	CostEstimate string `json:"cost_estimate"`
	// The hourly price of the instance in cents.
	HourlyPrice *int64 `json:"hourly_price,omitzero"`
	// How the instance is rented and on what terms.
	RentalTerms *RentalTerms `json:"rental_terms,omitzero"`
	// Defines automatic actions after the instance becomes active.
	LaunchConfiguration *LaunchConfiguration `json:"launch_configuration,omitzero"`
	// Add custom, searchable tags to instances.
	Tags []string `json:"tags,omitzero"`
	// List of port mappings on an instance that a Cloud Provider might have automatically set up.
	PortMappings []InstancePortMappings `json:"port_mappings,omitzero"`
	// The timestamp of when the instance was active in UTC.
	ActiveAt *time.Time `json:"active_at,omitzero"`
	// The timestamp of when the instance was created in UTC.
	CreatedAt time.Time `json:"created_at"`
	// The timestamp of when the instance was deleted in UTC.
	DeletedAt time.Time `json:"deleted_at"`
	BootTime  *BootTime `json:"boot_time,omitzero"`
}

func (i Instance) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *Instance) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *Instance) GetID() string {
	if i == nil {
		return ""
	}
	return i.ID
}

func (i *Instance) GetCloud() string {
	if i == nil {
		return ""
	}
	return i.Cloud
}

func (i *Instance) GetRegion() string {
	if i == nil {
		return ""
	}
	return i.Region
}

func (i *Instance) GetShadeInstanceType() string {
	if i == nil {
		return ""
	}
	return i.ShadeInstanceType
}

func (i *Instance) GetCloudInstanceType() string {
	if i == nil {
		return ""
	}
	return i.CloudInstanceType
}

func (i *Instance) GetCloudAssignedID() string {
	if i == nil {
		return ""
	}
	return i.CloudAssignedID
}

func (i *Instance) GetShadeCloud() bool {
	if i == nil {
		return false
	}
	return i.ShadeCloud
}

func (i *Instance) GetName() string {
	if i == nil {
		return ""
	}
	return i.Name
}

func (i *Instance) GetConfiguration() InstanceConfiguration {
	if i == nil {
		return InstanceConfiguration{}
	}
	return i.Configuration
}

func (i *Instance) GetIP() string {
	if i == nil {
		return ""
	}
	return i.IP
}

func (i *Instance) GetSSHUser() string {
	if i == nil {
		return ""
	}
	return i.SSHUser
}

func (i *Instance) GetSSHPort() int64 {
	if i == nil {
		return 0
	}
	return i.SSHPort
}

func (i *Instance) GetStatus() Status {
	if i == nil {
		return Status("")
	}
	return i.Status
}

func (i *Instance) GetStatusDetails() *string {
	if i == nil {
		return nil
	}
	return i.StatusDetails
}

func (i *Instance) GetCostEstimate() string {
	if i == nil {
		return ""
	}
	return i.CostEstimate
}

func (i *Instance) GetHourlyPrice() *int64 {
	if i == nil {
		return nil
	}
	return i.HourlyPrice
}

func (i *Instance) GetRentalTerms() *RentalTerms {
	if i == nil {
		return nil
	}
	return i.RentalTerms
}

func (i *Instance) GetLaunchConfiguration() *LaunchConfiguration {
	if i == nil {
		return nil
	}
	return i.LaunchConfiguration
}

func (i *Instance) GetTags() []string {
	if i == nil {
		return nil
	}
	return i.Tags
}

func (i *Instance) GetPortMappings() []InstancePortMappings {
	if i == nil {
		return nil
	}
	return i.PortMappings
}

func (i *Instance) GetActiveAt() *time.Time {
	if i == nil {
		return nil
	}
	return i.ActiveAt
}

func (i *Instance) GetCreatedAt() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.CreatedAt
}

func (i *Instance) GetDeletedAt() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.DeletedAt
}

func (i *Instance) GetBootTime() *BootTime {
	if i == nil {
		return nil
	}
	return i.BootTime
}
