// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/sdkinternal/utils"
)

// InstanceType - Information about a specific instance type
type InstanceType struct {
	// Specifies the underlying cloud provider. See this [explanation](/getting-started/concepts#cloud-cloud-provider) for more details.
	Cloud string `json:"cloud"`
	// The Shadeform standardized instance type. See this [explanation](/getting-started/concepts#shade-instance-type-and-cloud-instance-type) for more details.
	ShadeInstanceType string `json:"shade_instance_type"`
	// The instance type for the underlying cloud provider. See this [explanation](/getting-started/concepts#shade-instance-type-and-cloud-instance-type) for more details.
	CloudInstanceType string                    `json:"cloud_instance_type"`
	Configuration     InstanceTypeConfiguration `json:"configuration"`
	// The hourly price of the instance in cents.
	HourlyPrice int64 `json:"hourly_price"`
	// Whether the instance is a "vm" (virtual machine), a "container" (docker container), or "baremetal" (bare metal server).
	DeploymentType string         `json:"deployment_type"`
	Availability   []Availability `json:"availability"`
	BootTime       *BootTime      `json:"boot_time,omitzero"`
}

func (i InstanceType) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InstanceType) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InstanceType) GetCloud() string {
	if i == nil {
		return ""
	}
	return i.Cloud
}

func (i *InstanceType) GetShadeInstanceType() string {
	if i == nil {
		return ""
	}
	return i.ShadeInstanceType
}

func (i *InstanceType) GetCloudInstanceType() string {
	if i == nil {
		return ""
	}
	return i.CloudInstanceType
}

func (i *InstanceType) GetConfiguration() InstanceTypeConfiguration {
	if i == nil {
		return InstanceTypeConfiguration{}
	}
	return i.Configuration
}

func (i *InstanceType) GetHourlyPrice() int64 {
	if i == nil {
		return 0
	}
	return i.HourlyPrice
}

func (i *InstanceType) GetDeploymentType() string {
	if i == nil {
		return ""
	}
	return i.DeploymentType
}

func (i *InstanceType) GetAvailability() []Availability {
	if i == nil {
		return []Availability{}
	}
	return i.Availability
}

func (i *InstanceType) GetBootTime() *BootTime {
	if i == nil {
		return nil
	}
	return i.BootTime
}
