// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/sdkinternal/utils"
)

// Type - Specifies the type of launch configuration. See [Launch Configuration](/getting-started/concepts#launch-configuration) for more details.
type Type string

const (
	TypeDocker Type = "docker"
	TypeScript Type = "script"
)

func (e Type) ToPointer() *Type {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Type) IsExact() bool {
	if e != nil {
		switch *e {
		case "docker", "script":
			return true
		}
	}
	return false
}

// LaunchConfiguration - Defines automatic actions after the instance becomes active.
type LaunchConfiguration struct {
	// Specifies the type of launch configuration. See [Launch Configuration](/getting-started/concepts#launch-configuration) for more details.
	Type Type `json:"type"`
	// May only be used if launch_configuration.type is 'docker'. Use docker_configuration to automatically pull and run a docker image. See this [tutorial](/guides/dockercontainers) for examples.
	DockerConfiguration *DockerConfiguration `json:"docker_configuration,omitzero"`
	// May only be used if launch_configuration.type is 'script'. Configures a startup script to be run automatically after the instance is active. See this [tutorial]/guides/startupscript) for examples.
	ScriptConfiguration *ScriptConfiguration `json:"script_configuration,omitzero"`
}

func (l LaunchConfiguration) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LaunchConfiguration) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *LaunchConfiguration) GetType() Type {
	if l == nil {
		return Type("")
	}
	return l.Type
}

func (l *LaunchConfiguration) GetDockerConfiguration() *DockerConfiguration {
	if l == nil {
		return nil
	}
	return l.DockerConfiguration
}

func (l *LaunchConfiguration) GetScriptConfiguration() *ScriptConfiguration {
	if l == nil {
		return nil
	}
	return l.ScriptConfiguration
}
