// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 351cf71a8a27

package components

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/sdkinternal/utils"
)

// Networking - Network configuration including firewall rules
type Networking struct {
	// List of UFW (Uncomplicated Firewall) rules
	UfwRules []UfwRule `json:"ufw_rules,omitzero"`
}

func (n Networking) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *Networking) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (n *Networking) GetUfwRules() []UfwRule {
	if n == nil {
		return nil
	}
	return n.UfwRules
}
