// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PortMappings - Maps the public instance port to a port on the container.
type PortMappings struct {
	// Port of the host.
	HostPort int64 `json:"host_port"`
	// Port of the container.
	ContainerPort int64 `json:"container_port"`
}

func (p *PortMappings) GetHostPort() int64 {
	if p == nil {
		return 0
	}
	return p.HostPort
}

func (p *PortMappings) GetContainerPort() int64 {
	if p == nil {
		return 0
	}
	return p.ContainerPort
}
