// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RegistryCredentials struct {
	// The username for the docker registry.
	Username *string `json:"username,omitzero"`
	// The password for the docker registry.
	Password *string `json:"password,omitzero"`
}

func (r *RegistryCredentials) GetUsername() *string {
	if r == nil {
		return nil
	}
	return r.Username
}

func (r *RegistryCredentials) GetPassword() *string {
	if r == nil {
		return nil
	}
	return r.Password
}
