// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/optionalnullable"
	"github.com/shadeform/shadeform-cli/internal/sdk/sdkinternal/utils"
	"time"
)

// RentalTermsRentalType - How the instance is rented.
type RentalTermsRentalType string

const (
	RentalTermsRentalTypeOnDemand   RentalTermsRentalType = "on_demand"
	RentalTermsRentalTypeSpot       RentalTermsRentalType = "spot"
	RentalTermsRentalTypeCommitment RentalTermsRentalType = "commitment"
)

func (e RentalTermsRentalType) ToPointer() *RentalTermsRentalType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *RentalTermsRentalType) IsExact() bool {
	if e != nil {
		switch *e {
		case "on_demand", "spot", "commitment":
			return true
		}
	}
	return false
}

// RentalTerms - How the instance is rented and on what terms.
type RentalTerms struct {
	// How the instance is rented.
	RentalType RentalTermsRentalType `json:"rental_type"`
	// The hourly price as a decimal string in dollars. A spot instance shows its discounted spot rate. Omitted for commitments.
	HourlyPrice *string `json:"hourly_price,omitzero"`
	// The promised end of the rental when one is known. Null for open-ended rentals. Spot instances are open-ended and can be reclaimed at any time, so this is null; a reclaim shows up as the instance moving to `deleting` with `status_details: "preempted"`.
	EndingAt optionalnullable.OptionalNullable[time.Time] `json:"ending_at,omitzero"`
}

func (r RentalTerms) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RentalTerms) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RentalTerms) GetRentalType() RentalTermsRentalType {
	if r == nil {
		return RentalTermsRentalType("")
	}
	return r.RentalType
}

func (r *RentalTerms) GetHourlyPrice() *string {
	if r == nil {
		return nil
	}
	return r.HourlyPrice
}

func (r *RentalTerms) GetEndingAt() optionalnullable.OptionalNullable[time.Time] {
	if r == nil {
		return nil
	}
	return r.EndingAt
}
