// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a2b007d91dd1

package components

// ScriptConfiguration - May only be used if launch_configuration.type is 'script'. Configures a startup script to be run automatically after the instance is active. See this [tutorial]/guides/startupscript) for examples.
type ScriptConfiguration struct {
	// A startup script that is base64 encoded.
	Base64Script string `json:"base64_script"`
}

func (s *ScriptConfiguration) GetBase64Script() string {
	if s == nil {
		return ""
	}
	return s.Base64Script
}
