// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c1a78fe12ea5

package components

type Security struct {
	APIKey string `security:"scheme,type=apiKey,subtype=header,name=X-API-KEY"`
}

func (s *Security) GetAPIKey() string {
	if s == nil {
		return ""
	}
	return s.APIKey
}
