// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d99ce12618e1

package components

type SSHKeysResponse struct {
	SSHKeys []SSHKey `json:"ssh_keys"`
}

func (s *SSHKeysResponse) GetSSHKeys() []SSHKey {
	if s == nil {
		return []SSHKey{}
	}
	return s.SSHKeys
}
