// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SSHKey struct {
	// The ID of the SSH Key.
	ID string `json:"id"`
	// The name of the SSH Key.
	Name string `json:"name"`
	// The public key.
	PublicKey string `json:"public_key"`
	// Indicates the default key.
	IsDefault bool `json:"is_default"`
}

func (s *SSHKey) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SSHKey) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *SSHKey) GetPublicKey() string {
	if s == nil {
		return ""
	}
	return s.PublicKey
}

func (s *SSHKey) GetIsDefault() bool {
	if s == nil {
		return false
	}
	return s.IsDefault
}
