// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: bf85eba857ca

package components

// Status - The status of the instance.
type Status string

const (
	StatusCreating        Status = "creating"
	StatusPendingProvider Status = "pending_provider"
	StatusPending         Status = "pending"
	StatusActive          Status = "active"
	StatusError           Status = "error"
	StatusDeleting        Status = "deleting"
	StatusDeleted         Status = "deleted"
)

func (e Status) ToPointer() *Status {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Status) IsExact() bool {
	if e != nil {
		switch *e {
		case "creating", "pending_provider", "pending", "active", "error", "deleting", "deleted":
			return true
		}
	}
	return false
}
