// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TemplatesResponse struct {
	Templates []Template `json:"templates"`
}

func (t *TemplatesResponse) GetTemplates() []Template {
	if t == nil {
		return []Template{}
	}
	return t.Templates
}
