// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 2883a403e8c4

package components

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/sdkinternal/utils"
)

type Template struct {
	// Unique identifier for the template, generated by Shadeform
	ID string `json:"id"`
	// Name of the template
	Name string `json:"name"`
	// Description of the template
	Description *string `json:"description,omitzero"`
	// Author of the template
	Author *string `json:"author,omitzero"`
	// URL to the template's logo
	Logo *string `json:"logo,omitzero"`
	// Whether the template is publicly available
	Public *bool `json:"public,omitzero"`
	// Defines automatic actions after the instance becomes active.
	LaunchConfiguration *LaunchConfiguration `json:"launch_configuration,omitzero"`
	// Set a date or spend threshold to automatically delete the instance
	AutoDelete *AutoDelete `json:"auto_delete,omitzero"`
	// Set a date or spend threshold to receive an email alert
	Alert *Alert `json:"alert,omitzero"`
	// Settings for mounting volumes onto file systems
	VolumeMount *VolumeMount `json:"volume_mount,omitzero"`
	// Add custom, searchable tags to instances.
	Tags []string `json:"tags,omitzero"`
	// List of environment variable name and values to automatically add to the instance
	Envs []Env `json:"envs,omitzero"`
	// Network configuration including firewall rules
	Networking *Networking `json:"networking,omitzero"`
}

func (t Template) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *Template) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *Template) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *Template) GetName() string {
	if t == nil {
		return ""
	}
	return t.Name
}

func (t *Template) GetDescription() *string {
	if t == nil {
		return nil
	}
	return t.Description
}

func (t *Template) GetAuthor() *string {
	if t == nil {
		return nil
	}
	return t.Author
}

func (t *Template) GetLogo() *string {
	if t == nil {
		return nil
	}
	return t.Logo
}

func (t *Template) GetPublic() *bool {
	if t == nil {
		return nil
	}
	return t.Public
}

func (t *Template) GetLaunchConfiguration() *LaunchConfiguration {
	if t == nil {
		return nil
	}
	return t.LaunchConfiguration
}

func (t *Template) GetAutoDelete() *AutoDelete {
	if t == nil {
		return nil
	}
	return t.AutoDelete
}

func (t *Template) GetAlert() *Alert {
	if t == nil {
		return nil
	}
	return t.Alert
}

func (t *Template) GetVolumeMount() *VolumeMount {
	if t == nil {
		return nil
	}
	return t.VolumeMount
}

func (t *Template) GetTags() []string {
	if t == nil {
		return nil
	}
	return t.Tags
}

func (t *Template) GetEnvs() []Env {
	if t == nil {
		return nil
	}
	return t.Envs
}

func (t *Template) GetNetworking() *Networking {
	if t == nil {
		return nil
	}
	return t.Networking
}
