// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 7f56a4f74b09

package components

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/sdkinternal/utils"
)

type TemplateSaveRequest struct {
	// Name of the template
	Name string `json:"name"`
	// Description of the template
	Description *string `json:"description,omitzero"`
	// Whether the template is publicly available
	Public *bool `json:"public,omitzero"`
	// Defines automatic actions after the instance becomes active.
	LaunchConfiguration *LaunchConfiguration `json:"launch_configuration,omitzero"`
	// Set a date or spend threshold to automatically delete the instance
	AutoDelete *AutoDelete `json:"auto_delete,omitzero"`
	// Set a date or spend threshold to receive an email alert
	Alert *Alert `json:"alert,omitzero"`
	// Settings for mounting volumes onto file systems
	VolumeMount *VolumeMount `json:"volume_mount,omitzero"`
	// Tags associated with the template
	Tags []string `json:"tags,omitzero"`
	// Environment variables for the template
	Envs []Env `json:"envs,omitzero"`
	// Network configuration including firewall rules
	Networking *Networking `json:"networking,omitzero"`
}

func (t TemplateSaveRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TemplateSaveRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TemplateSaveRequest) GetName() string {
	if t == nil {
		return ""
	}
	return t.Name
}

func (t *TemplateSaveRequest) GetDescription() *string {
	if t == nil {
		return nil
	}
	return t.Description
}

func (t *TemplateSaveRequest) GetPublic() *bool {
	if t == nil {
		return nil
	}
	return t.Public
}

func (t *TemplateSaveRequest) GetLaunchConfiguration() *LaunchConfiguration {
	if t == nil {
		return nil
	}
	return t.LaunchConfiguration
}

func (t *TemplateSaveRequest) GetAutoDelete() *AutoDelete {
	if t == nil {
		return nil
	}
	return t.AutoDelete
}

func (t *TemplateSaveRequest) GetAlert() *Alert {
	if t == nil {
		return nil
	}
	return t.Alert
}

func (t *TemplateSaveRequest) GetVolumeMount() *VolumeMount {
	if t == nil {
		return nil
	}
	return t.VolumeMount
}

func (t *TemplateSaveRequest) GetTags() []string {
	if t == nil {
		return nil
	}
	return t.Tags
}

func (t *TemplateSaveRequest) GetEnvs() []Env {
	if t == nil {
		return nil
	}
	return t.Envs
}

func (t *TemplateSaveRequest) GetNetworking() *Networking {
	if t == nil {
		return nil
	}
	return t.Networking
}
