// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 4bbcfe9aa6cc

package components

// TemplateCreateResponse - Response of the /templates/save API call
type TemplateCreateResponse struct {
	// The unique identifier for the instance. Used in the instances for the /instances/{id}/info and /instances/{id}/delete APIs.
	ID string `json:"id"`
}

func (t *TemplateCreateResponse) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}
