// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c9e7f26a9e65

package components

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/optionalnullable"
)

// UfwRule - Uncomplicated Firewall rule configuration
type UfwRule struct {
	// The UFW rule action
	Rule *string `json:"rule,omitzero"`
	// Source IP address or CIDR range
	FromIP optionalnullable.OptionalNullable[string] `json:"from_ip,omitzero"`
	// Destination IP address or CIDR range
	ToIP optionalnullable.OptionalNullable[string] `json:"to_ip,omitzero"`
	// Port number or range (e.g. '80' or '8000:8999')
	Port optionalnullable.OptionalNullable[string] `json:"port,omitzero"`
	// Protocol (e.g. tcp, udp)
	Proto optionalnullable.OptionalNullable[string] `json:"proto,omitzero"`
}

func (u *UfwRule) GetRule() *string {
	if u == nil {
		return nil
	}
	return u.Rule
}

func (u *UfwRule) GetFromIP() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.FromIP
}

func (u *UfwRule) GetToIP() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.ToIP
}

func (u *UfwRule) GetPort() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.Port
}

func (u *UfwRule) GetProto() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.Proto
}
