// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/shadeform/shadeform-cli/internal/sdk/sdkinternal/utils"
)

type UpdateRequest struct {
	// The name of the instance
	Name *string `json:"name,omitzero"`
	// Set a date or spend threshold to automatically delete the instance
	AutoDelete *AutoDelete `json:"auto_delete,omitzero"`
	// Set a date or spend threshold to receive an email alert
	Alert *Alert `json:"alert,omitzero"`
	// Add custom, searchable tags to instances.
	Tags []string `json:"tags,omitzero"`
}

func (u UpdateRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateRequest) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateRequest) GetAutoDelete() *AutoDelete {
	if u == nil {
		return nil
	}
	return u.AutoDelete
}

func (u *UpdateRequest) GetAlert() *Alert {
	if u == nil {
		return nil
	}
	return u.Alert
}

func (u *UpdateRequest) GetTags() []string {
	if u == nil {
		return nil
	}
	return u.Tags
}
