// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type VolumesTypesResponse struct {
	VolumeTypes []VolumeTypes `json:"volume_types"`
}

func (v *VolumesTypesResponse) GetVolumeTypes() []VolumeTypes {
	if v == nil {
		return []VolumeTypes{}
	}
	return v.VolumeTypes
}
