// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c53053f85966

package components

// VolumeMounts - Mounts the host volume to a container file path.
type VolumeMounts struct {
	// Filepath of the host.
	HostPath string `json:"host_path"`
	// Filepath of the container.
	ContainerPath string `json:"container_path"`
}

func (v *VolumeMounts) GetHostPath() string {
	if v == nil {
		return ""
	}
	return v.HostPath
}

func (v *VolumeMounts) GetContainerPath() string {
	if v == nil {
		return ""
	}
	return v.ContainerPath
}
