// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 73e0cd1f5e7e

package components

type VolumeTypes struct {
	// Specifies the underlying cloud provider. See this [explanation](/getting-started/concepts#cloud-cloud-provider) for more details.
	Cloud string `json:"cloud"`
	// Specifies the region.
	Region string `json:"region"`
	// Denotes whether the volume supports multiple instances mounting to it at the same time.
	SupportsMultiMount bool `json:"supports_multi_mount"`
	// Denotes whether the volume is fixed in size or elastically scaling.
	FixedSize bool `json:"fixed_size"`
	// Price of the specified volume type per GB per hour
	PricePerGbPerHour string `json:"price_per_gb_per_hour"`
}

func (v *VolumeTypes) GetCloud() string {
	if v == nil {
		return ""
	}
	return v.Cloud
}

func (v *VolumeTypes) GetRegion() string {
	if v == nil {
		return ""
	}
	return v.Region
}

func (v *VolumeTypes) GetSupportsMultiMount() bool {
	if v == nil {
		return false
	}
	return v.SupportsMultiMount
}

func (v *VolumeTypes) GetFixedSize() bool {
	if v == nil {
		return false
	}
	return v.FixedSize
}

func (v *VolumeTypes) GetPricePerGbPerHour() string {
	if v == nil {
		return ""
	}
	return v.PricePerGbPerHour
}
