// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 6ba13e71d37e

package components

type VolumesResponse struct {
	Volumes []Volume `json:"volumes"`
}

func (v *VolumesResponse) GetVolumes() []Volume {
	if v == nil {
		return []Volume{}
	}
	return v.Volumes
}
