// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// VolumeMount - Settings for mounting volumes onto file systems
type VolumeMount struct {
	// Set to true to automatically mount unmounted disks to a default filesystem.
	Auto *bool `json:"auto,omitzero"`
}

func (v *VolumeMount) GetAuto() *bool {
	if v == nil {
		return nil
	}
	return v.Auto
}
