// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 11ac77e58c3a

package components

type Volume struct {
	// The ID of the storage volume.
	ID string `json:"id"`
	// Specifies the underlying cloud provider. See this [explanation](/getting-started/concepts#cloud-cloud-provider) for more details.
	Cloud string `json:"cloud"`
	// The unique identifier of the storage volume issued by the underlying cloud provider.
	CloudAssignedID string `json:"cloud_assigned_id"`
	// Specifies the region.
	Region string `json:"region"`
	// The name of the storage volume.
	Name string `json:"name"`
	// Denotes whether the volume is fixed in size or elastically scaling.
	FixedSize bool `json:"fixed_size"`
	// Storage volume size in GB
	SizeInGb int64 `json:"size_in_gb"`
	// The cost incurred by the instance. This only the cost via Shadeform. If the instance is deployed in your own cloud account, then all billing is through your cloud provider.
	CostEstimate string `json:"cost_estimate"`
	// Denotes whether the volume supports multiple instances mounting to it at the same time.
	SupportsMultiMount bool `json:"supports_multi_mount"`
	// The ID of the instance that is currently mounting the volume.
	MountedBy string `json:"mounted_by"`
}

func (v *Volume) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *Volume) GetCloud() string {
	if v == nil {
		return ""
	}
	return v.Cloud
}

func (v *Volume) GetCloudAssignedID() string {
	if v == nil {
		return ""
	}
	return v.CloudAssignedID
}

func (v *Volume) GetRegion() string {
	if v == nil {
		return ""
	}
	return v.Region
}

func (v *Volume) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *Volume) GetFixedSize() bool {
	if v == nil {
		return false
	}
	return v.FixedSize
}

func (v *Volume) GetSizeInGb() int64 {
	if v == nil {
		return 0
	}
	return v.SizeInGb
}

func (v *Volume) GetCostEstimate() string {
	if v == nil {
		return ""
	}
	return v.CostEstimate
}

func (v *Volume) GetSupportsMultiMount() bool {
	if v == nil {
		return false
	}
	return v.SupportsMultiMount
}

func (v *Volume) GetMountedBy() string {
	if v == nil {
		return ""
	}
	return v.MountedBy
}
